### ISSUE TITLE
Ignoring tags after creation

### ISSUE THREAD

**Issue by jcooklin** [crossplane/crossplane#3843] opened 2023-03-09 17:25 UTC
### What happened?

AWS resource tags are updated by an out-of-band process and we need a way to tell Crossplane (providers) to ignore tags after creation.  This process crawls the account and tags all resources for tracking related to cost attribution.

### What environment did it happen in?
crossplane: v1.10.2
Using upbound/provider-aws or crossplane-contrib/provider-aws

_Originally posted by @stevendborrelli in https://github.com/crossplane/crossplane/pull/3822#discussion_r1129902067_

**Comment by negz** [comment] 2023-03-09 20:37
Thanks for raising this! @lsviben is actually working on a design for this in https://github.com/crossplane/crossplane/pull/3822. I'm going to close this as a duplicate of https://github.com/crossplane/crossplane/issues/3516 - let's track this there.

**Closed by negz** 2023-03-09 20:37 UTC
