### ISSUE TITLE
Support patch from Kubernetes secrets 

### ISSUE THREAD

**Issue by ArunRamakani** [crossplane/crossplane#3057] opened 2022-04-26 05:26 UTC
### What problem are you facing?

Secrets created in one XR are required in another XR. Allow patching of secrets in the compositions. 

Nested XR is not an option as we need to have segregation of concerns between XR as a design option. 

### How could Crossplane help solve your problem?

Core Kubernetes APIs already have this pattern. For example, Pod specification can refer to a secret for the environment variable. 

Or we need a referencing mechanism in composition to refer to the status field of one XR from another without nesting the XRs (We have this in MRs today)

**Comment by MisterMX** [comment] 2022-04-26 14:56
Duplicate of #2099

**Closed** 2022-04-26 18:08 UTC
Labels: enhancement
