### ISSUE TITLE
Support merging, rather than replacing objects

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#2211] opened 2021-03-13 04:21 UTC
### What problem are you facing?

We're seeing a common pattern emerging in `Compositions`:

```yaml
  patchSets:
  - name: Metadata
    patches:
    - fromFieldPath: metadata.labels
    - fromFieldPath: metadata.annotations
 ```

This patchset will replicate the XR's labels and annotations to each of its composed resources. A potential issue with this approach is that the [`fieldpath` package](https://pkg.go.dev/github.com/crossplane/crossplane-runtime@v0.13.0/pkg/fieldpath) package replaces objects - it does not merge them. Crossplane can store some important information about each composed resource in their annotations - for example the `crossplane.io/external-name` annotation controls the actual name of a resource in an external system in cases where that name should not be derived from the managed resource's Kubernetes `metadata.name`. It's possible for a managed resource to accidentally orphan an external resource if this information is patched over.

### How could Crossplane help solve your problem?

Crossplane could support configurable merge semantics when patching objects, perhaps using something like https://github.com/imdario/mergo or a JSON merge patch (https://tools.ietf.org/html/rfc7386). Ideally we would:

* Maintain the current behaviour by default, and replace the entire destination object.
* Support optionally merging in only keys that don't exist in the destination object.
* Support optionally replacing any key that exists in the destination object if the same key exists in the source object.

**Comment by muvaf** [comment] 2021-05-08 23:58
@ulucinar would you be interested in tackling this issue? It touches one of the lower level libraries that composition uses, so it'd be a great chance to expose yourself to composition internals.

**Comment by ulucinar** [comment] 2021-05-09 00:05
Hi @muvaf,
Thank you for bringing this up. Yes, definitely it looks like a good opportunity.  I'm assigning it to myself then.

**Comment by ulucinar** [comment] 2021-06-03 13:56
It seems like we have two issues here:

1. The composite reconciler, while rendering composed resources, can lose certain info when applying patches. An example to this issue is if the patch set of the composed template contains a patch for `metadata.annotations` as in the above example, then the `crossplane.io/composition-resource-name` annotation gets lost while applying patches (assuming template name is specified). I think this issue is related solely to the composition reconciler, i.e., it does not cause a race condition between multiple controllers, and in my opinion, it can be considered as a bug of the composition reconciler. 
1. The `resource.APIUpdatingApplicator`, which is employed by the composite reconciler for updating composed resources,  already [does](https://github.com/crossplane/crossplane-runtime/blob/ded177829557d53d10f0e4b2b9fb5c6edb594aef/pkg/resource/api.go#L157) an RFC7386 (json-merge) patch. During this patch operation, for instance, any annotations also set by another controller are replaced. If the `RDSInstance` controller of provider-aws has already set the `crossplane.io/external-name` annotation and the patch set contains a patch for `metadata.annotations` from the XR, then because XR also contains the annotation `crossplane.io/external-name`, it will be overridden as expected by the `resource.APIUpdatingApplicator`'s patch operation. 


Regarding [2] above, my understanding is that this will be the behavior regardless of the patch type we use ([json-merge](https://datatracker.ietf.org/doc/html/rfc7386) or [json](https://datatracker.ietf.org/doc/html/rfc6902) patch). These types of patches will both replace already existing items. So, I think as suggested in the issue description, using a library such as [mergo](https://github.com/imdario/mergo), we need to be able to exclude items not to be replaced from patch specification. The patch specification document is prepared by the `resource.APIUpdatingApplicator` and it currently serializes the desired composed resource into JSON to get the patch specification. We may extend its behavior so that, _optionally for certain paths_ of the JSON object being patched, it will be able to use `mergo` to merge the _desired_ contents onto the actual contents of the path observed in the cluster. We cannot simply merge the whole desired JSON object (representation of the composed resource) on the actual one, because I think we do want to reconcile (have it replaced by the composite reconciler) certain paths. For instance, if the XR for a postgresql instance specifies a storage size for the composed `RDSInstance`, and an external entity modifies the storage size in the composed `RDSInstance` resource, we would still like it to be reconciled to the value declared in the parent XR by the composite reconciler. 

An example for turning on the merge behavior declaratively for certain paths with the patch specifition in the composed resource template may be as follows:

```yaml
 patchSets:
  - name: Metadata
    patches:
    - fromFieldPath: metadata.annotations
      policy:
        mergeOptions:
          keep: true
```
This proposes to extend the `v1.PatchPolicy` struct with the `MergeOptions` member:
```go
type MergeOptions struct {
	Keep        bool
	AppendSlice bool
    ...
}
```

We may readily extend `MergeOptions` with other flags supported by `mergo` or with other options that we implement. But the specification of the `Keep` option would direct the `resource.APIUpdatingApplicator` to turn on merging behavior for the corresponding JSON path (if this is supported, i.e., if, at the specified patch path, lives a struct or a map) and the merge will not override the already existing items under that path if `keep=true`. If `MergeOptions` is not specified, we will be preversing the exact old behavior (no merging even) for backwards compability. 

Regarding [1] above, I believe we should unconditionally invoke the merge logic during rendering for supported types (structs and maps) when applying the patches found in the composed resource's template. Because, my understanding is that the rendering phase does not involve the actual (current) state of the composed resource in the cluster and outputs the desired state, so we had better not override any fields set during rendering when applying patches. If this is accepted, the behavior will change but as explained above, I would consider this as a bug fix.

@negz what are your thoughts on these points? If we are on the same page, I'd like to continue with the implementation I've started.

**Comment by ulucinar** [comment] 2021-06-03 14:02
Also, if the above proposal of `MergeOptions` is okay, should we have some _declarative_ names instead of the imperative ones exemplified above, e.g., `keep: true` -> `kept: true` or `notOverridden: true`? Not sure but the imperative ones sound more natural but I think they are not in tandem with the API conventions.

**Comment by muvaf** [comment] 2021-06-03 15:18
@ulucinar Thank you for the write-up!

Regarding [2]:
> The resource.APIPatchingApplicator, which is employed by the composite reconciler for updating composed resources, already does an RFC7386 (json-merge) patch. During this patch operation, for instance, any annotations also set by another controller are replaced. If the RDSInstance controller of provider-aws has already set the crossplane.io/external-name annotation and the patch set contains a patch for metadata.annotations from the XR, then because XR also contains the annotation crossplane.io/external-name, it will be overridden as expected by the resource.APIPatchingApplicator's patch operation.

If I understood you correctly, I think this is actually the desired behavior, i.e. if user specifies a value in XR such as `crossplane.io/external-name` annotation (which is how we [import](https://crossplane.io/docs/v1.2/concepts/managed-resources.html#importing-existing-resources) resources), it should replace whatever is in the `RDSInstance` even if set by other entities because XR is the source of truth for all composed resources as long as it has a value for those fields. The reason we use [`APIPatchingApplicator`](https://github.com/crossplane/crossplane/blob/f7f477c/internal/controller/apiextensions/composite/reconciler.go#L296) is so that we don't touch the late-initialized fields, i.e. the ones that XR doesn't have a value for but set by provider-aws such as default values. FWIW, there is a difference with upstream patching mechanisms that we calculate the patch body [ourselves](https://github.com/crossplane/crossplane-runtime/blob/84dc59d/pkg/resource/api.go#L158) as the full object.

Regarding [1]:
> An example to this issue is if the patch set of the composed template contains a patch for `metadata.annotations` as in the above example, then the `crossplane.io/composition-resource-name` annotation gets lost while applying patches (assuming template name is specified)

I don't really understand why we lose the existing annotations that we don't have value for. For example, if I create a patch like the following, the existing annotations do not disappear from the target resource:
```yaml
# original
apiVersion: apps/v1
kind: Deployment
metadata:
  name: patch-demo
  annotations:
    initial-key: initial-value
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: patch-demo-ctr
        image: nginx
---
# patch
apiVersion: apps/v1
kind: Deployment
metadata:
  name: patch-demo
  annotations: {}
spec:
  replicas: 1
```
```
kubectl patch deployment patch-demo --type merge --patch "$(cat empty-anno.yaml)"
# or
kubectl patch deployment patch-demo --type strategic --patch "$(cat empty-anno.yaml)"
```

Quoting from original issue description:
> This patchset will replicate the XR's labels and annotations to each of its composed resources. A potential issue with this approach is that the fieldpath package package replaces objects - it does not merge them.

This should actually be OK from my tests with `kubectl patch` and what I read. Why in our case, when we send an empty `metadata.annotations` or one with keys without `crossplane.io/external-name` in the patch, we see `crossplane.io/external-name` removed from the composed resource? It's actually really hard to remove a map field in the target object during a patch call but we do it somehow.

**Comment by ulucinar** [comment] 2021-06-03 15:31
The issue mentioned in [1] is not related to json patch or json-merge patch, API server is not involved there. It's related with replacing values via the `fieldpath` library in the composite controller itself. We may, for example, overcome it by first merging  the patch source value with any existing values without overriding existing content and then call `fieldpath`'s `SetValue` with the merged value.

**Comment by ulucinar** [comment] 2021-06-03 15:45
> Why in our case, when we send an empty metadata.annotations or one with keys without crossplane.io/external-name in the patch, we see crossplane.io/external-name removed from the composed resource?

The `crossplane.io/external-name` annotation is removed from the composed resource's set of annotations because the XR has that annotation (with an empty string value). Thanks for the question @muvaf, actually this was something I was planning to mention but forgot to include in the initial write-up. So the behavior is expected as you mentioned, and that's why I would classify [1] as a bug but not [2] (which is also the reason the `crossplane.io/external-name` annotation set by managed resource's controller is overridden). 

If the user of the template patching API does not want this behavior, currently we do not provide the necessary feature (e.g., a `MergeOptions` API described above) yet.

**Comment by ulucinar** [comment] 2021-06-03 15:51
As discussed in slack, here is a snippet from an XR provisioned via a claim:
```yaml
apiVersion: database.example.org/v1alpha1
kind: CompositePostgreSQLInstance
metadata:
  annotations:
    crossplane.io/external-name: ""
...
```
It contains the `crossplane.io/external-name` annotation, which causes the managed resource's annotation to be overridden.

**Comment by muvaf** [comment] 2021-06-03 15:52
> The issue mentioned in [1] is not related to json patch or json-merge patch, API server is not involved there. It's related with replacing values via the fieldpath library in the composite controller itself. 

> The crossplane.io/external-name annotation is removed from the composed resource's set of annotations because the XR has that annotation (with an empty string value)

Yeah I just noticed that when I was testing. Apparently we propagate the external name back to claim even if it's empty and then the propagation flow is claim -> composite -> managed resource if `metadata.annotations` or even `metadata.annotations[crossplane.io/external-name]` is given and no external name annotation set in claim. So, doing [this](https://github.com/crossplane/crossplane/blob/ec0b383/internal/controller/apiextensions/claim/configurator.go#L66) and [that](https://github.com/crossplane/crossplane/blob/b9a8f4b/internal/controller/apiextensions/claim/api.go#L67) operation only if the external name is empty seems to solve this problem.

**Comment by ulucinar** [comment] 2021-06-03 15:55
So, should we open bugs for these, and maybe reserve this issue for the feature request mentioned in [2] above?

**Comment by muvaf** [comment] 2021-06-03 16:00
I think `Support merging, rather than replacing objects` is valid for [1] but not much for the empty external name propagation bug even though we thought one is the cause of other. A separate issue for setting an empty external name could make sense.

**Comment by muvaf** [comment] 2021-06-03 18:57
Here is the issue specific to the external-name problem https://github.com/crossplane/crossplane/issues/2350

**Comment by negz** [comment] 2021-06-03 19:05
/points 8

(Just a guess - mostly trying to make sure the points command works).

**Comment by muvaf** [comment] 2021-06-11 15:32
I'd suggest the following API to follow the existing [conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#primitive-types):
```yaml
patchSets:
  - name: Metadata
    patches:
    - fromFieldPath: metadata.annotations
      policy:
        strategy: Merge|Replace
```

**Closed** 2021-08-17 20:42 UTC
Labels: enhancement, composition, points/8
