### ISSUE TITLE
Unable configure "false" for boolean properties.

### ISSUE THREAD

**Issue by gowrisankar22** [crossplane/crossplane#1802] opened 2020-10-05 05:36 UTC
### What happened?

I have created my own infra which is RDS and I made it a few values as configurable required values. After this I am unable to configure boolean properties to "false". It always expects true.

**InfraDef**
```
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: InfrastructureDefinition
metadata:
  name: postgresqlinstances.database.example.org
spec:
  connectionSecretKeys:
    - username
    - password
    - endpoint
    - port
  crdSpecTemplate:
    group: database.example.org
    version: v1alpha1
    names:
      kind: PostgreSQLInstance
      listKind: PostgreSQLInstanceList
      plural: postgresqlinstances
      singular: postgresqlinstance
    validation:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  storageGB:
                    type: integer
                  Version:
                    description: postgres engine version
                    type: string
                  MultiAZ:
                    description: enable multiaz for RDS server
                    type: boolean
                  Backup:
                    description: enable automated backups immediately, choose a positive nonzero value
                    type: integer
                  Encryption:
                    description: enable the encryption for DB
                    type: boolean
                required:
                  - storageGB
                  - Version
                  - MultiAZ
                  - Backup
                  - Encryption
            required:
              - parameters
```

**Composition**
```
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: Composition
metadata:
  name: postgresqlinstances.aws.database.example.org
  labels:
    provider: aws
    guide: quickstart
    vpc: default
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  reclaimPolicy: Delete
  #deletionPolicy: orphan
  from:
    apiVersion: database.example.org/v1alpha1
    kind: PostgreSQLInstance
  to:
    - base:
        apiVersion: database.aws.crossplane.io/v1beta1
        kind: RDSInstance
        spec:
          forProvider:
            dbInstanceClass: db.t2.small
            masterUsername: masteruser
            engine: postgres
            #engineVersion: "9.6"
            skipFinalSnapshotBeforeDeletion: true
            publiclyAccessible: true
          writeConnectionSecretToRef:
            namespace: crossplane-system
          providerRef:
            name: aws-provider
          reclaimPolicy: Delete
      patches:
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-postgresql"
        - fromFieldPath: "spec.parameters.storageGB"
          toFieldPath: "spec.forProvider.allocatedStorage"
        - fromFieldPath: "spec.parameters.Version"
          toFieldPath: "spec.forProvider.engineVersion"
        - fromFieldPath: "spec.parameters.Backup"
          toFieldPath: "spec.forProvider.backupRetentionPeriod"
        - fromFieldPath: "spec.parameters.MultiAZ"
          toFieldPath: "spec.forProvider.multiAZ"
        - fromFieldPath: "spec.parameters.Encryption"
          toFieldPath: "spec.forProvider.storageEncrypted"
      connectionDetails:
        - fromConnectionSecretKey: username
        - fromConnectionSecretKey: password
        - fromConnectionSecretKey: endpoint
        - fromConnectionSecretKey: port
```

**instance**
```

apiVersion: database.example.org/v1alpha1
kind: PostgreSQLInstanceRequirement
metadata:
  name: my-db-rds
  namespace: default
spec:
  parameters:
    storageGB: 20
    Version: "11"
    MultiAZ: true
    Backup: 2
    Encryption: true
  compositionSelector:
    matchLabels:
      provider: aws
      vpc: default
  writeConnectionSecretToRef:
    name: db-conn

```

I am unable to make `Encryption & MultiAZ` value to false. it always expects true. This applies to all other boolean properties.
-->

### How can we reproduce it?

just apply this to reproduce the issue.
```
apiVersion: database.example.org/v1alpha1
kind: PostgreSQLInstanceRequirement
metadata:
  name: my-db-rds
  namespace: default
spec:
  parameters:
    storageGB: 20
    Version: "11"
    MultiAZ: false
    Backup: 2
    Encryption: false
  compositionSelector:
    matchLabels:
      provider: aws
      vpc: default
  writeConnectionSecretToRef:
    name: db-conn
```

### What environment did it happen in?
Crossplane version: 0.12(latest)

Include at least the version or commit of Crossplane you were running. Consider
also including your:

* Cloud provider or hardware configuration: AWS 
* Kubernetes version (use `kubectl version`): 1.16
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift)
* OS (e.g. from /etc/os-release)
* Kernel (e.g. `uname -a`)
-->

**Comment by negz** [comment] 2020-10-05 06:14
@gowrisankar22 Thanks for the bug report. I have one question to help understand your issue.

> After this I am unable to configure boolean properties to "false". It always expects true.

Do you mean that the value of `spec.forProvider.multiAZ` and `spec.forProvider.storageEncrypted` are `true` in your composed `RDSInstance`, even when you set `spec.parameters.MultiAZ` and `spec.parameters.Encryption` to `false` in your `PostgreSQLInstanceRequirement`? Or do you mean that the API server rejects your request when you attempt to create a `PostgreSQLInstanceRequirement` with `spec.parameters.MultiAZ: false` or `spec.parameters.Encryption: false`?

**Comment by gowrisankar22** [comment] 2020-10-05 07:22
@negz 
API server rejects my request and it works with only `true`

**Comment by muvaf** [comment] 2020-10-05 11:14
I am trying to reproduce the issue. I have created the `InfrastructureDefinition`, `Composition` you posted as well as the `InfrastructurePublication` and the rbac permissions as shown in guide https://crossplane.io/docs/v0.12/getting-started/publish-infrastructure.html

Then I created the following:
```yaml

apiVersion: database.example.org/v1alpha1
kind: PostgreSQLInstanceRequirement
metadata:
  name: my-db-rds
  namespace: default
spec:
  parameters:
    storageGB: 20
    Version: "11"
    MultiAZ: false
    Backup: 2
    Encryption: false
  compositionSelector:
    matchLabels:
      provider: aws
      vpc: default
  writeConnectionSecretToRef:
    name: db-conn
```

My composite resource looks like:
```yaml
apiVersion: database.example.org/v1alpha1
kind: PostgreSQLInstance
metadata:
  creationTimestamp: "2020-10-05T10:48:22Z"
  generateName: my-db-rds-
  generation: 4
  labels:
    crossplane.io/composite: my-db-rds-8bqgw
    crossplane.io/requirement-name: my-db-rds
    crossplane.io/requirement-namespace: default
  name: my-db-rds-8bqgw
  resourceVersion: "2057"
  selfLink: /apis/database.example.org/v1alpha1/postgresqlinstances/my-db-rds-8bqgw
  uid: 637fd908-b979-4354-80f3-127aa264dfc1
spec:
  compositionRef:
    name: postgresqlinstances.aws.database.example.org
  compositionSelector:
    matchLabels:
      provider: aws
      vpc: default
  parameters:
    Backup: 2
    Encryption: false
    MultiAZ: false
    Version: "11"
    storageGB: 20
  reclaimPolicy: Delete
  requirementRef:
    name: my-db-rds
    namespace: default
  resourceRefs:
  - apiVersion: database.aws.crossplane.io/v1beta1
    kind: RDSInstance
    name: my-db-rds-8bqgw-dhwgp
    uid: f2835c82-04bf-4a71-8eb8-fc1744ee47f9
  writeConnectionSecretToRef:
    name: 637fd908-b979-4354-80f3-127aa264dfc1
    namespace: crossplane-system
status:
  conditions:
  - lastTransitionTime: "2020-10-05T10:48:23Z"
    reason: Resource is being created
    status: "False"
    type: Ready
  - lastTransitionTime: "2020-10-05T10:48:23Z"
    reason: Successfully reconciled resource
    status: "True"
    type: Synced
```

And `RDSInstance` is created successfully:
```yaml
apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  annotations:
    crossplane.io/external-name: my-db-rds-8bqgw-dhwgp
  creationTimestamp: "2020-10-05T10:48:23Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: my-db-rds-8bqgw-
  generation: 65
  labels:
    crossplane.io/composite: my-db-rds-8bqgw
    crossplane.io/requirement-name: my-db-rds
    crossplane.io/requirement-namespace: default
  name: my-db-rds-8bqgw-dhwgp
  ownerReferences:
  - apiVersion: database.example.org/v1alpha1
    controller: true
    kind: PostgreSQLInstance
    name: my-db-rds-8bqgw
    uid: 637fd908-b979-4354-80f3-127aa264dfc1
  resourceVersion: "4648"
  selfLink: /apis/database.aws.crossplane.io/v1beta1/rdsinstances/my-db-rds-8bqgw-dhwgp
  uid: f2835c82-04bf-4a71-8eb8-fc1744ee47f9
spec:
  forProvider:
    allocatedStorage: 20
    autoMinorVersionUpgrade: true
    availabilityZone: us-west-2d
    backupRetentionPeriod: 2
    caCertificateIdentifier: rds-ca-2019
    copyTagsToSnapshot: false
    dbInstanceClass: db.t2.small
    dbSubnetGroupName: default
    deletionProtection: false
    enableIAMDatabaseAuthentication: false
    enablePerformanceInsights: false
    engine: postgres
    engineVersion: "11.8"
    licenseModel: postgresql-license
    masterUsername: masteruser
    monitoringInterval: 0
    multiAZ: false
    port: 5432
    preferredBackupWindow: 10:20-10:50
    preferredMaintenanceWindow: sat:06:36-sat:07:06
    publiclyAccessible: true
    skipFinalSnapshotBeforeDeletion: true
    storageEncrypted: false
    ...
status:
  atProvider:
    ...
  conditions:
  - lastTransitionTime: "2020-10-05T10:54:55Z"
    reason: Resource is available for use
    status: "True"
    type: Ready
  - lastTransitionTime: "2020-10-05T10:48:26Z"
    reason: Successfully reconciled resource
    status: "True"
    type: Synced
```

@gowrisankar22 could you try to reproduce again?

**Comment by gowrisankar22** [comment] 2020-10-06 02:41
Sure. Let me give it a try :)

**Comment by muvaf** [comment] 2020-10-06 07:52
Closing the issue, feel free to reopen with latest YAMLs if you can reproduce in a fresh new cluster.

**Closed by muvaf** 2020-10-06 07:52 UTC
Labels: bug
