### ISSUE TITLE
XRC -> XR Label Propagation Confuses ArgoCD

### ISSUE THREAD

**Issue by idallaserra** [crossplane/crossplane#2121] opened 2021-02-05 17:14 UTC
Edit from @negz:

> In the case of an XR created by an XRC, ArgoCD sees a XR appear with the application ownership label (currently automatically propagated by Crossplane), but without an owner reference to any known resource

I believe, per @mcavoyk's comment above, that this is the key issue we're seeing here. ArgoCD thinks _it_ (not Crossplane) created the XR, because when Crossplane creates the XR it propagates a label ArgoCD uses to track which resource it owns. This results in the XR either being shown as "out-of-sync" or being deleted depending on whether auto-prune is enabled.

Original issue follows.

---

Dear all,
in the scenario we are testing we deploy on a k8s cluster crossplane and all the resources taked from [platform-ref-gcp](https://github.com/upbound/platform-ref-gcp) except the final resource of the example folder.
These last resources  for example triggering the [Cluster creation](https://github.com/upbound/platform-ref-gcp/blob/main/examples/cluster.yaml) was done using ArgoCD that formally connect to the k8s cluster and execute the yaml.
Flagging the [auto-pruning feature]( https://argoproj.github.io/argo-cd/user-guide/auto_sync/) of ArgoCD leads to a sort of resource contentions between Crossplane and Argo:

`Normal   ConfigureCompositeResource  19s (x3 over 20s)  offered/compositeresourcedefinition.apiextensions.crossplane.io  Successfully applied composite resource
  Warning  ConfigureCompositeResource  19s (x2 over 20s)  offered/compositeresourcedefinition.apiextensions.crossplane.io  cannot patch object: Operation cannot be fulfilled on compositenetworks.gcp.platformref.crossplane.io "test-network-d6xjh": the object has been modified; please apply your changes to the latest version and try again
  Normal   BindCompositeResource       18s (x3 over 20s)  offered/compositeresourcedefinition.apiextensions.crossplane.io  Composite resource is not yet ready
  Warning  BindCompositeResource       18s                offered/compositeresourcedefinition.apiextensions.crossplane.io  compositenetworks.gcp.platformref.crossplane.io "test-network-d6xjh" not found`

and the Cluster was not created.
Disabling auto-pruning indeed lead to the resource creation, but Argo remain out-of-sync.
In my opinion the correct ways is to having all the crd and definiton of gcp-reference done by Argo, not only the last one.
So I am not sure if is actually a bug or not, or simple an usage misunderstanding.
Thanks,
Ivan

**Comment by negz** [comment] 2021-02-09 01:38
Thanks for raising this issue @idallaserra! I'm not personally very familiar with ArgoCD. Can you help me understand exactly what the auto-pruning feature is trying to do? Is it trying to undo changes that Crossplane controllers are making to the `kind: Cluster` (for example is it trying to remove the `spec.compositeRef.name` and `spec.resourceRef.name` fields that Crossplane sets automatically?

**Comment by muvaf** [comment] 2021-02-09 13:16
From what I can tell, ArgoCD deletes the composed resources that are created by Crossplane in order to keep git repo fully authoritative and in-sync all the time. Though I wonder how it'd handle `Pod`s created by `Deployment`s, that's essentially the same mechanism with Crossplane creating managed resources when it sees the composite resource.

**Comment by benagricola** [comment] 2021-02-09 14:54
This is very similar to what I've been seeing with Argo - if you have prune enabled on an application, it will remove any resources it doesn't manage directly itself.

It can be avoided by applying `argocd.argoproj.io/sync-options: Prune=false` as an annotation to each resource that ArgoCD should not manage, but right now it isn't possible to apply that annotation to the Composite resource created from a Claim against an XRD (outlined in #2000). Argo will delete the Composite resource created from a Claim, causing Crossplane to part-create and then delete the underlying resources over and over.

Right now you have to disable prune on the Argo application itself, but with #2000 implemented you could set the annotation on the XRD, Composite and underlying resources so these are all managed by Crossplane, leaving the Claim resource managed by Argo.

**Comment by braghettos** [comment] 2021-02-09 17:35
If you keep _Prune=false_ then ArgoCD will be always in "out of sync" mode, that is not something that you would like to see in a gitops approach

**Comment by negz** [comment] 2021-02-09 19:41
Thanks folks. It sounds like we should address this by finding a solution to https://github.com/crossplane/crossplane/issues/2000, which should let Argo know that it should manage the claim but not the resulting XR, and thus leave the XR alone. To @muvaf's point I think it's unrealistic to expect ArgoCD to directly manage every resource in the API server. Having ArgoCD model and manage a claim's XR and composed resources would be like having argo model and manage a Deployment's ReplicaSets and Pods.

**Comment by mcavoyk** [comment] 2021-02-16 05:06
> Though I wonder how it'd handle Pods created by Deployments, that's essentially the same mechanism with Crossplane creating managed resources when it sees the composite resource.

My understanding from using ArgoCD and a quick scan through some of logic is that generated resources are not pruned if they have a [known parent resource](https://github.com/argoproj/gitops-engine/blob/v0.2.1/pkg/cache/cluster.go#L636), e.g. the `Pod` is not pruned because in its ownership hierarchy is a `Deployment` that is part of the git repo. There are some [exceptions ](https://github.com/argoproj/gitops-engine/blob/v0.2.1/pkg/cache/references.go#L21) made for `Endpoints` and for `PersistentVolumeClaim`'s created by `StatefulSets`.

Creating a XR with ArgoCD doesn't experience this pruning issue, as all the generated resources may end up with the ArgoCD application ownership label (if `metadata.labels` is patched on the Compositions), but the generated provider resources all have ownership references set to the XR.

In the case of an XR created by an XRC, ArgoCD sees a XR appear with the application ownership label (currently automatically propagated by Crossplane), but without an owner reference to any known resource. Attempting to disable ArgoCD prune via their available annotation is not really effective in this case, as the primary means to apply it to the XR is through adding to the XRC, which means the XRC is unable to be deleted by ArgoCD.

**Comment by muvaf** [comment] 2021-02-17 08:21
@mcavoyk thank you for detailed explanation!

> There are some exceptions made for Endpoints and for PersistentVolumeClaim's created by StatefulSets.

We want to come up with a good solution for this labeling stuff but I see that some exceptions are added for coreos operator group in ArgoCD. Do you think we can add an exception to cover claim <> composite relationship? The reason composite doesn't have an ownerRef is that claim is namespaced and composite is cluster-scoped and apiserver doesn't allow a namespaced resource to own a cluster-scoped one. The exception would look at `spec.claimRef` to figure out whether it's created by a known claim.

**Comment by kelvinwijaya** [comment] 2021-03-02 17:47
Hi All,

Recently i also encounter similar error message mentioned above in my composite resource (pardon me about the unconventional format of the k8s event logs as it is generated by the Alert tool):

Exactly 2 Warning Events generated in the namespace where the Claim Resource residing:
```
Description: Error Occurred in MyBucket: mynamespace/test-s3 in dev cluster
cannot update composite resource: Operation cannot be fulfilled on abc.com "test-s3-2j97g": the object has been modified; please apply your changes to the latest version and try again

abc.com/v1alpha1/mybuckets error
Description: Error Occurred in MyBucket: mynamespace/test-s3 in dev cluster
cannot patch object: Operation cannot be fulfilled on abc.com "test-s3-2j97g": the object has been modified; please apply your changes to the latest version and try again
```

I am currently using ArgoCD for Claim Resource deployment and also to overcome the `auto-pruning` issue, I have also included ArgoCD settings for `resource.exclusions` [Ref] https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#resource-exclusioninclusion] and applied it to the Composite and Managed Resource Kind. With this setup in place, ArgoCD wont do the auto-syncing (nor it will delete the object that is not managed by them). This method might help solving the ArgoCD behavior for @benagricola @idallaserra 


My suspicion is if there are other Reconciler process that has updated the Composite Resource which causing its `resourceversion` to be different and became fail while the Claim Reconciler try to update it. 
Also fyi, I don't recall having this error message before i upgraded to crossplane v1.0.0 and updated the xrd apiVersion to `apiextensions.crossplane.io/v1`.

**Comment by muvaf** [comment] 2021-03-03 08:09
@kelvinwijaya these errors should be safe to skip as long as they don't happen continuously since the claim controller will make the same update in the next reconcile with the updated composite object.

**Comment by kelvinwijaya** [comment] 2021-03-04 04:41
Hi @muvaf 

Just to understand a bit on the problem, does it mean there are 2 controllers (composite & claim) that is trying to update the composite object as the same time which caused race condition?  
Also are you trying to explain that eventually the claim controller will make sure the composite object to be updated during the binding process?

Thanks

**Comment by muvaf** [comment] 2021-03-04 19:00
> does it mean there are 2 controllers (composite & claim) that is trying to update the composite object as the same time which caused race condition?

Yes, this is possible and intended. This error is thrown when the resource that controller A will update changes between the start of its reconciliation and the end. So, all setups where two controllers make any operation on the same resource is subject to this. Though, reconciliation makes sure the resource is consistent eventually.

**Comment by empath-nirvana** [comment] 2022-01-21 20:42
The problem is actually:

1) Argocd adds an annotation to every resource it creates directly.
2) If a resource isn't in the manifest source that argo is syncing from, but does have an annotation, argo assumes that it was installed by argo, but it no longer is desired, so it wants to prune it.  
3) Crossplane is propogating annotations to resources it creates, including argocd annotations.
4) Argo wants to prune everything that crossplane is generating.

**Comment by natereid72** [comment] 2022-02-09 17:19
> 

I don't see that behavior with Argo CD and Crossplane. What I see is Argo CD not adding any annotations for Crossplane or other resources (e.g. Deployment -> RS -> Pod). From what I've observed, Argo CD accepts a resource that is not defined in repo so long as it has a K8s ownership reference reference chain for anything downstream from what is in the repo.

K8s will not allow the namespace scoped XRC to show ownership for cluster scoped XR. So everything from XR through downstream resources are considered out of sync with repo and, if enabled, Argo CD will want to prune them. If starting with XR, all downstream resources are accepted via the owner reference to XR.

So by either configuring Argo CD to ignore XR and down, or starting with XR alone, the relationship is lost between XRC and XR. By ignoring XR, nothing will show in the Argo CD tracked app beyond XRC and it will show Sync'd. It seems preferable to see XRC -> MR, so this seems it will require either for K8s to allow a namespace scoped resource to show ownership of a cluster scoped resource, or for Argo CD to implement an understanding of the relationship betweeen Crossplane XRC -> XR.

**Comment by natereid72** [comment] 2022-02-18 21:02
Open for thoughts on this premise: In GitOps, we can use GitOps platform RBAC, Git repo approval requirements, and K8s RBAC+Policy to control where a Git repo source can deploy to. So for Global/Cluster scoped XR, we should be ok to have our workflow begin there. This eliminates the 'out of sync' issue with ArgoCD. Of the benefits XRC offers, being able to pass namespace into Composition assists with ProviderConfig selection when multiple ProviderConfigs exist and users of one namepsace should only use the one intended for them. All other XRC benefits can be accomplished with via GitOps platform config and process in Git approval. If we enhance the string transform type `TrimPrefix` to trim up to a character, then we could prefix all of the ArgoCD Application names with namespace, trim that out from XR, and use in Composition for ProviderConfig selection. I am certain there are some holes in this premise, please let me know if you see/find any.

**Comment by natereid72** [comment] 2022-02-25 22:10
I've compiled my findings into #2928 

I believe it covers the reason for every issue described here.

**Comment by James-Quigley** [comment] 2022-03-02 19:41
Adding the annotation `argocd.argoproj.io/compare-options: IgnoreExtraneous` to the XRC works. The XR and MRs will show up in the UI, but won't be considered when evaluating the sync status

**Comment by natereid72** [comment] 2022-03-02 20:10
@James-Quigley I'm not sure how that would work. That tells ArgoCD to ignore the resource. So it will ignore the XRC too if I read docs correctly. When I set it, I see this.
![image](https://user-images.githubusercontent.com/45366367/156440028-7ef599d7-f7e4-46b4-8852-7f0b272a8e8e.png)

**Comment by natereid72** [comment] 2022-08-13 22:41
Revive

**Comment by nabuskey** [comment] 2022-08-18 23:14
As of ArgoCD 2.4.8, the new annotation based tracking works with xr and xrc with auto pruning enabled. Application shows as synced and health is reflected correctly. XR does not get auto-pruned. 

One caveat is that XRs will show as root resources instead of them being "children" of claims. 

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/21176944/185510440-611c6856-767b-4679-b98e-e770c0ad2385.png">

**Comment by natereid72** [comment] 2022-08-22 21:15
@negz I propose closing this issue based on @nabuskey comment.

**Comment by thradec** [comment] 2022-08-25 10:33
Hi, did you use any additional configuration/tuning, I have a recent version of ArgoCD 2.4.11 and still struggling with the pruning of XRs.

**Comment by thradec** [comment] 2022-08-25 12:08
Sorry, I missed the `application.resourceTrackingMethod: annotation`, with it,  it's working great, thx.

**Comment by jbw976** [comment] 2022-08-25 15:51
> @negz I propose closing this issue based on @nabuskey comment.

I think we could close this when #3041 is merged - that provides guidance on how to configure Argo, `application.resourceTrackingMethod: annotation`, etc. to work well with Crossplane 🤓

**Closed** 2022-09-02 23:58 UTC
Labels: bug, help wanted, good first issue, argocd

**Comment by mcanevet** [comment] 2023-01-03 10:44
I had to enable clusterResourceWhitelist on the specific group I'm using on my AppProjet so that I can see the  Composite Resource in ArgoCD. But if I understand correctly, this would also allow my users to explicitly declare Composite Resources or even Managed Resources without using Claims. Is it true? Is there any workaround?

**Comment by lukegAtPaxos** [comment] 2024-01-12 11:26
This doesn't seem like a reasonable fix, shouldn't RD Claims that generate XRD's propagate ownership references, along with claim references. Wouldn't this correct the hierarchy issue in Argo and bring XRD's into scope of the project? At the moment, it seems that an misconfiguration in Argo could wipe out infrastructure using crossplane.  

FunctionRevsions for example correctly specify the owner reference and link to the Function

![image](https://github.com/crossplane/crossplane/assets/97543497/9cef620b-349d-4c88-bb41-3c033621d7f8)

```
apiVersion: pkg.crossplane.io/v1beta1
kind: FunctionRevision
metadata:
  creationTimestamp: '2024-01-12T10:50:59Z'
  finalizers:
    - revision.pkg.crossplane.io
  generation: 1
  labels:
    pkg.crossplane.io/package: terraform-example
  name: terraform-example-714659823149
  ownerReferences:
    - apiVersion: pkg.crossplane.io/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: Function
      name: terraform-example
      uid: c50856f8-9a89-454a-9cfc-103057d92005
```
