### ISSUE TITLE
Adding a new EnvironmentConfig to an existing Composite isn't respected

### ISSUE THREAD

**Issue by djmcgreal-cc** [crossplane/crossplane#5490] opened 2024-03-18 10:21 UTC
### What happened?

An existing Composite had a single `environmentConfigRefs`. Adding a second to the `Composition` should be reflected in the Composite but isn't. Adding in the newly added environment config manually works and is not overwritten by subsequent reconciliations.

### How can we reproduce it?
Make a Composition with a Managed Resource that includes references an EnvironmentConfig and make a Composite out of it. Update the Composition to reference a second EnvironmentConfig and observe the Composite still only references the initial EnvironmentConfig.

### What environment did it happen in?
Crossplane version: crossplane-1.14.6

**Comment by phisco** [comment] 2024-03-18 10:26
You need to set `spec.environment.policy.Resolve: Always` or delete the XR's `spec.environmentConfigRefs` for that to happen, that's by design. FYI: with [function-environment-configs](https://github.com/crossplane-contrib/function-environment-configs) that's the default (and only) behaviour right now, see https://github.com/crossplane-contrib/function-environment-configs/issues/6.

**Comment by djmcgreal-cc** [comment] 2024-03-18 10:49
Thanks. Cherry on the top would be some status feedback reflecting the discrepancy.

**Comment by phisco** [comment] 2024-06-14 09:13
Closing this as we are going to deprecate it and should be handled by functions instead, e.g. https://github.com/crossplane-contrib/function-environment-configs

**Closed by phisco** 2024-06-14 09:13 UTC
Labels: bug
