### ISSUE TITLE
[xfn] Avoid resourceVersion change on no-op

### ISSUE THREAD

**Issue by duizabojul** [crossplane/crossplane#4409] opened 2023-07-30 22:03 UTC
This is an edit of the issue after having a chat with upbound team and we found the real underlying issue.

## Context

We heavily use xfn function in our compositions to do some templating. During templating we start from desired resources as provided by crossplane controller and we modify them. Modifications are a combination of adding/removing/modifying fields, adding/removing resources (we implemented things like if and for loops).

## Observation

We observed some composed resources getting patched every time composition function runs (so every 60s), giving a lot of extra work to our providers (provider-aws in our case). Odd behavior is the patch only bumps `resourceVersion` field, there is no change in manifest except this field.

So every minute we have 10s of no-op patches triggering terraform plans in provider-aws, a 8cpu machine under heavy load and ttls issues with terraform process.

## Cause

After some investigation we found that the we outputed some "bad" fields in desired resources, and after some cleaning in our xfn process, the issue was resolved.

![Before/After two rounds of cleaning](https://github.com/crossplane/crossplane/assets/7392946/7192892c-7692-400f-a33e-9dcf2cffd169)

The screenshot show two rounds of cleaning on our side. No-op patches were caused by:

- Outputing wrong metadata like `generation` field different from the real one. Desired resources have these metadata set if there is no corresponding observed resource, but unset if there is. If you modify the name of the desired resource to match an already generated resource (we are doing this in our implementation of for loop), and you forgot to clean metadata, you will get the no-op patch.
- Outputing empty arrays/objects on already empty fields: these fields are removed at the end (by k8s api?) but cause a no-op patch

I don't know who is the real responsible of these no-op patches but maybe crossplane controller should clean resources to avoid them. As seen on screenshot it can be a real pain and it is pretty hard to debug.

**Comment by jeanduplessis** [comment] 2023-07-31 00:47
@duizabojul we are currently focusing on improving the performance of the Upbound providers. The next release will have some improvement, but we are actively working on evaluating changes that could yield substantial performance improvement. 

Would you be willing to have a sync chat so we can understand your specific scenario, share with you what we are planning and use your use case as a test benchmark? If you're open to it feel free to reach out to me on the Crossplane Slack.

**Comment by duizabojul** [comment] 2023-08-05 09:59
@jeanduplessis I updated the issue

**Comment by negz** [comment] 2023-09-01 23:26
@duizabojul Could you please:

 * Check whether this happens if you enable the functions feature flag, but don't specify any functions
 * Check whether this happens if you disable the functions feature flag

That will help me get an idea of where the problem is. Thanks!

**Comment by duizabojul** [comment] 2023-09-01 23:55
I don't think it can happens without running function. The only  way to reproduce this is to output  "bad" things from xfn pipeline.

**Comment by negz** [comment] 2023-09-13 21:55
@duizabojul I'm pretty confident #4500 fixed this by switching the `FunctionComposer` to use server-side apply. I'm going to close this - could you ping me if you notice it's still an issue with the new implementation and I'll reopen it.

**Closed by negz** 2023-09-13 21:55 UTC
Labels: composition, functions
