### ISSUE TITLE
Problem deploying composition revisions in configuration packages

### ISSUE THREAD

**Issue by wilhelmi** [crossplane/crossplane#3015] opened 2022-03-30 19:30 UTC
Hit stumbling block with composition revision and configuration packages. Revisions are enabled in Crossplane 1.7.0, when I make changes to the composition locally and apply them they work as expected. I get multiple revisions, and I can point the claim to the desired revision.

Next step was to package up the changes. Created 2 packages each representing the stages I ran through above. When I apply the first package, I can create the claim and all works as expected.

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
 name: test-package-3
 namespace: crossplane-system
spec:
 package: gcr.io/....crossplane/demo:0.0.3
```
However when I try to install the second configuration package the new composition revision never gets installed

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
 name: test-package-4
 namespace: crossplane-system
spec:
 package: gcr.io/..../crossplane/demo:0.0.4
```

This seems to be the relevant error event:

cannot establish control of object: xtests.demo.com is already controlled by ConfigurationRevision test-package-3-b2857c468e58 (UID 1b6214f9-e997-4708-8025-1f028847ead4)

**Comment by wilhelmi** [comment] 2022-03-31 20:30
Same problem with 1.6.4, first package will deploy to a healthy state, second package fails.

**Comment by wilhelmi** [comment] 2022-03-31 22:47
@negz as the driver of revisions, is it possible to package revisions up as packages, reading some package docs leaning towards this not being possible?

**Comment by negz** [comment] 2022-07-26 23:34
@wilhelmi Just to make sure I'm following, are you literally putting a CompositionRevision in the package, or just a Composition? The former is not intended to work, but the latter should.

Cross-linking https://github.com/crossplane/crossplane/issues/2656 so we make sure to factor this in when we start work promoting CompositionRevisions to v1beta1.

**Comment by wilhelmi** [comment] 2022-07-26 23:55
@negz Just putting a composition in a package,  I was expected new CompositionRevision to be created when when packages were deployed.

**Comment by ezgidemirel** [comment] 2022-11-01 15:17
Hey @wilhelmi, noticed that you're using different `metadata.name`s in your manifests. Do you have a use case for that? I think what you observe is expected regardless of composition revisions.

**Comment by ezgidemirel** [comment] 2022-11-08 07:27
Closing the issue, because it seems like expected behavior. Please feel free to reopen and provide further details if you disagree.

**Closed by ezgidemirel** 2022-11-08 07:27 UTC
Labels: bug

**Comment by monta-riahi** [comment] 2025-05-13 19:27
@ezgidemirel I happened to reproduce a similar error I applied a configuration, then deleted it then reapplied it and it shows 
`apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
 name: test-package-3
 namespace: crossplane-system
spec:
 package: gcr.io/....crossplane/demo:0.0.3`

>  cannot establish control of object: xpo ││ diamroles.iam.crossplane.cimpress.io is already controlled by Conf ││ igurationRevision configuration-quickstart-3888ebcd28cf (UID 03dd9 │
> │ 1ed-5e45-47ec-af80-f417bf538712)

**Comment by ezgidemirel** [comment] 2025-05-14 11:08
Hi @monta-riahi, after deleting the configuration, did you give API server enough time to clean up the configurationrevision resource?

**Comment by monta-riahi** [comment] 2025-05-14 12:56
Hi @ezgidemirel , no I did it almost instantly.

**Comment by ezgidemirel** [comment] 2025-05-15 13:20
Hi @monta-riahi, that might be the issue. Could you try reapplying it once you’ve confirmed the configurationrevision is removed?
