### ISSUE TITLE
NewCompositionRevisionTransform SIGSEGV on string TrimPrefix transform

### ISSUE THREAD

**Issue by jwjs36987** [crossplane/crossplane#3130] opened 2022-06-08 20:57 UTC
### What happened?
When using a string transform of TrimPrefix the crossplane manager hits a SIGSEGV

```
I0608 20:45:35.082407       1 request.go:665] Waited for 1.024645739s due to client-side throttling, not priority and fairness, request: GET:https://172.20.0.1:443/apis/policy/v1?timeout=32s
{"level":"info","ts":1654721139.6404533,"logger":"crossplane","msg":"Alpha feature enabled","flag":"EnableAlphaCompositionRevisions"}
I0608 20:45:39.731531       1 leaderelection.go:248] attempting to acquire leader lease crossplane-system/crossplane-leader-election-core...
I0608 20:46:41.276050       1 leaderelection.go:258] successfully acquired lease crossplane-system/crossplane-leader-election-core
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x155f1f3]

goroutine 776 [running]:
github.com/crossplane/crossplane/internal/controller/apiextensions/composition.NewCompositionRevisionTransform(...)
        /home/runner/work/crossplane/crossplane/internal/controller/apiextensions/composition/revision.go:164
github.com/crossplane/crossplane/internal/controller/apiextensions/composition.NewCompositionRevisionPatch({{0xc00085f170, 0x14}, 0xc0020b0e50, 0x0, 0xc0020b0e60, 0x0, {0xc001f3bb30, 0x1, 0x1}, 0x0})
        /home/runner/work/crossplane/crossplane/internal/controller/apiextensions/composition/revision.go:142 +0x413
github.com/crossplane/crossplane/internal/controller/apiextensions/composition.NewCompositionRevisionComposedTemplate({0xc0020b0de0, {{0xc001f467e0, 0x111, 0x111}, {0x0, 0x0}}, {0xc001e7aea0, 0x5, 0x5}, {0xc0000eac80, ...}, ...})
        /home/runner/work/crossplane/crossplane/internal/controller/apiextensions/composition/revision.go:101 +0x258
github.com/crossplane/crossplane/internal/controller/apiextensions/composition.NewCompositionRevisionSpec({{{0xc0005d0810, 0x2c}, {0xc000b0dd35, 0xb}}, {0x0, 0x0, 0x0}, {0xc0020bc000, 0x9, 0x9}, ...}, ...)
        /home/runner/work/crossplane/crossplane/internal/controller/apiextensions/composition/revision.go:69 +0x3e5
github.com/crossplane/crossplane/internal/controller/apiextensions/composition.NewCompositionRevision(0xc001e68480, 0x209bec8, {0xc0020b3020, 0x10})
        /home/runner/work/crossplane/crossplane/internal/controller/apiextensions/composition/revision.go:38 +0x187
github.com/crossplane/crossplane/internal/controller/apiextensions/composition.(*Reconciler).Reconcile(0xc0007eb170, {0x209bf00, 0xc001f3ba10}, {{{0x0, 0xc001f07c30}, {0xc000b1c940, 0x30}}})
        /home/runner/work/crossplane/crossplane/internal/controller/apiextensions/composition/reconciler.go:196 +0x14c5
github.com/crossplane/crossplane-runtime/pkg/ratelimiter.(*Reconciler).Reconcile(0xc0003f7b80, {0x209bf00, 0xc001f3ba10}, {{{0x0, 0x1ce80a0}, {0xc000b1c940, 0x30}}})
        /home/runner/work/crossplane/crossplane/vendor/github.com/crossplane/crossplane-runtime/pkg/ratelimiter/reconciler.go:54 +0x16b
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc0000c6000, {0x209bf00, 0xc001f3b9e0}, {{{0x0, 0x1ce80a0}, {0xc000b1c940, 0x413ab4}}})
        /home/runner/work/crossplane/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:114 +0x26f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0000c6000, {0x209be58, 0xc0006e7c40}, {0x1bd53e0, 0xc00081e080})
        /home/runner/work/crossplane/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:311 +0x33e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0000c6000, {0x209be58, 0xc0006e7c40})
        /home/runner/work/crossplane/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /home/runner/work/crossplane/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /home/runner/work/crossplane/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:223 +0x357
```

### How can we reproduce it?

Launch crossplane with composition revisions enabled and create a composition which includes the following patch on a resource:

```yaml
patches:
  - type: ToCompositeFieldPath
    fromFieldPath: status.atProvider.identity.oidc.issuer
    toFieldPath: status.oidcName
    transforms:
    - type: string
      string:
        type: TrimPrefix
        trim: 'https://'
```

### What environment did it happen in?
Crossplane version:  v1.7.1, v1.7.2, v1.8.1
With composition revisions enabled.
Running on eks with provider-aws & provider-kubernetes

**Comment by jwjs36987** [comment] 2022-06-08 20:58
I think the issue is with https://github.com/crossplane/crossplane/blob/9715681117c17dead1e189969e717094cb899383/internal/controller/apiextensions/composition/revision.go#L164

which assumes that any string transform is a format transform

**Comment by negz** [comment] 2022-06-14 00:55
Yeah, I think this is the same issue as https://github.com/crossplane/crossplane/issues/3113. Thank you for the report!

**Comment by negz** [comment] 2022-06-23 01:06
Going to close this as a duplicate of #3113.

**Closed by negz** 2022-06-23 01:06 UTC
Labels: bug, composition
