### ISSUE TITLE
Please backport volume and volumeMount support for controllerConfig to release-1.12

### ISSUE THREAD

**Issue by nl-brett-stime** [crossplane/crossplane#4168] opened 2023-06-10 03:47 UTC
### What problem are you facing?

Volume support was added to master via #4037 . However, it wasn't backported to the release-1.12 branch in this repo (it was backported in upbound/crossplane but not here in crossplane/crossplane: https://github.com/upbound/crossplane/pull/88).

### How could Crossplane help solve your problem?

Please release volume support in the community repo. It'd be useful for uploading AWS Lambda code via S3 BucketObject.

Thanks!

**Comment by phisco** [comment] 2023-06-11 13:06
Hi, we usually backport only fixes and not features to release branches, we did that for `upbound/crossplane` because we needed to.
However could you better describe your use-case with lambda code via S3?

**Comment by nl-brett-stime** [comment] 2023-06-12 04:26
> could you better describe your use-case with lambda code via S3?

Thanks. We're working on transitioning to Crossplane. The Lambda Function CRD expects a reference to a zip file containing the Lambda's logic via an s3Key. The BucketObject CRD seems like a good way to ensure the files are present on S3. It'd be helpful to be able to take some code that was built/transpiled on the host (running k8s via kind) and set that as the source for the Bucket Object CRD. Currently, when applying a BucketObject spec, it doesn't seem to read from the host. My guess is that it's trying to read from some container guest or other. I'd like to ensure that it has access to the files it needs.

Lambda: https://marketplace.upbound.io/providers/upbound/provider-aws/v0.35.0/resources/lambda.aws.upbound.io/Function/v1beta1#doc:spec-forProvider-s3Key

BucketObject: https://marketplace.upbound.io/providers/upbound/provider-aws/v0.35.0/resources/s3.aws.upbound.io/BucketObject/v1beta1#doc:spec-forProvider-source

**Comment by negz** [comment] 2023-06-13 15:50
Just seconding @phisco here. I don't think we should back port this, unfortunately, since it's a new feature and not a bug fix.

**Comment by jbw976** [comment] 2023-06-14 08:12
Thanks for your interest in this feature @nl-brett-stime and thanks @phisco and @negz for weighing in here on the release and patching policy.  this is captured in the following doc: https://docs.crossplane.io/knowledge-base/guides/release-cycle/#definition-of-maintenance

This new feature will be included in v1.13 which is scheduled for late July.  Feel free to try out the latest RC build from master if you want to test this feature in a non-production environment. Closing this issue for now since the release cadence is scheduled.

**Closed by jbw976** 2023-06-14 08:12 UTC
Labels: enhancement
