### ISSUE TITLE
Reduce InfrastructureDefinition boilerplate by having Crossplane generate ClusterRole for users

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1653] opened 2020-07-14 13:23 UTC
### What problem are you facing?

For every new CRD, there needs to be some roles/clusterroles in the cluster that need to be bound to the users who'd like to create instances of those new types. Since InfraDef / InfraPub resources result in CRDs, `ClusterRole`s need to be created for each of them and that process is manual.

The documentation covers the permissions to grant to Crossplane itself, but this issue is more about helping users to create the defined resources.

### How could Crossplane help solve your problem?

Crossplane can create `ClusterRole`s for each InfraDef and InfraPub resources and later on, users can bind those `ClusterRole`s to `ServiceAccount`s either via `RoleBinding`s or `ClusterRoleBinding`s.

**Comment by negz** [comment] 2020-08-21 04:58
I think this is a duplicate of https://github.com/crossplane/crossplane/issues/1637.

**Closed by negz** 2020-08-21 04:58 UTC
Labels: composition, enhancement
