### ISSUE TITLE
Publish credentials to Vault

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1424] opened 2020-04-15 15:31 UTC
### What problem are you facing?

Crossplane publishes sensitive connection information of cloud resources Kubernetes Secrets. But I'd like them to be published to my Vault so that it can be accessed by other systems completely separate from Crossplane or cluster that it runs inside.

### How could Crossplane help solve your problem?

Publish connection secrets to a Vault instance with a custom operator or let the user mark resources via an annotation to tell that their connection secrets should be published to Vault directly.

**Comment by negz** [comment] 2020-06-30 03:14
I think this is a duplicate of https://github.com/crossplane/crossplane/issues/1009.

**Comment by rltvty** [comment] 2020-09-14 03:57
This is not a duplicate of #1009 

@muvaf is talking about secrets created by crossplane.  for example the connection details to a postgres database.  It would be great if these could be pushed to a vault instance instead of a kubernetes secret.

**Comment by gowrisankar22** [comment] 2020-10-01 13:03
It would be great if crossplane provides the integration to any of the external credential management systems. Example: vault ,credhub etc ...

Also, it would be also interesting to publish credentials to respective providers kms service.

```
aws-provider -- aws kms service
azure-provider -- azure kms service
gcp-provider -- gcp kms service
Alibaba-provider -- alibaba kms service
```

**Comment by lukeweber** [comment] 2020-11-02 17:07
I think it's also an interesting idea to consider whether someone would like to read their cloud provider credentials from an external vault, and only use shorter lived keys derived from the vault.

To make a change one could use a write token, and then switch back to a read token to validate state.

**Comment by negz** [comment] 2021-08-02 19:30
I'm going to roll this into https://github.com/crossplane/crossplane/issues/2366. This issue is older, but that issue captures the slightly broader scope we'd like to design for - e.g. supporting many secret stores, not just Kubernetes secrets and Vault.

**Closed by negz** 2021-08-02 19:30 UTC
Labels: enhancement
