### ISSUE TITLE
Incorrect Sync status on Composition (XRC) level when managed resource failed to synced on lifecycle.prevent_destroy event

### ISSUE THREAD

**Issue by jeanduplessis** [crossplane/crossplane#5209] opened 2024-01-10 08:36 UTC
### What happened?
Reposting from https://github.com/upbound/provider-gcp/issues/437 as reported by @vitalybronshtein.
The issue relates to core Crossplane, not the provider.

---

No indication on Claim ( XRC ) level that managed resource failed to synced on `immutable` fields 

For example when I'm update `machineType` in `NodePool` managed resource ( immutable filed ) , managed resource change status to `SYNCED=false` with `lifecycle.prevent_destroy error` , but no indication on XRC level that one of the resources failed to SYNCED , and claim status is `SYNCED=true`

- Manager resource event : 
```
Warning  CannotObserveExternalResource  14s (x6 over 52s)  managed/container.gcp.upbound.io/v1beta1, kind=nodepool  cannot run plan: plan failed: Instance cannot be destroyed: Resource google_container_node_pool.test-gke has lifecycle.prevent_destroy set, but the plan calls for this resource to be destroyed. To avoid this error and continue with the plan, either disable lifecycle.prevent_destroy or reduce the scope of the plan using the -target flag.
```

- Managed resource status (SYNCED=False)
```
kubectl get nodepools.container.gcp.upbound.io
NAME              READY   SYNCED   EXTERNAL-NAME     AGE
test-gke   True    False    test-gke   98m
```

- Claim status (SYNCED=true):
```
kubectl get gkeclusters.cloud.crossplane.io
NAME              SYNCED   READY   COMPOSITION                                      AGE
test-gke   True     True    gkeclusters.cloud.crossplane.io   99m
```

### What environment did it happen in?

Crossplane Version: v1.14.4
Provider Version: upbound-provider-gcp:v0.38.0
Kubernetes Version: v1.25.200
Kubernetes Distribution: GKE

**Comment by phisco** [comment] 2024-01-10 10:47
This is intended behaviour, `Synced` condition set to `True` means that the reconciliation loop succeeded for the resource, so in this case the Claim (XRC) reconciliation did succeed, same goes for the Composite Resource (XR), but then obviously the Managed Resource (MR) did not because of the error above.

We propagate back the `Ready` condition according to the `readinessChecks` defined by the Composition, so if the error resulted in the resource being marked as not ready that would be shown by the XR and XRC. So, one could configure the readinessChecks to also check the Synced condition of composed resources, but I'd classify that more as a hack than a solution.

**Comment by negz** [comment] 2024-01-17 20:14
As @phisco said, this is working as intended.

**Closed by negz** 2024-01-17 20:14 UTC
Labels: bug

**Comment by dilyankostov** [comment] 2024-03-19 17:09
The original bug was about changing an immutable field of an MR. This made the MR not Synced and erroring but the composition was silent. 

How should this be handled by customers? If I want to change the immutable field of an MR in a composition.
