### ISSUE TITLE
Can't fully rely on Vault as the only secret store

### ISSUE THREAD

**Issue by jonnylangefeld** [crossplane/crossplane#3823] opened 2023-03-07 01:00 UTC
I followed [these docs](https://docs.crossplane.io/v1.9/guides/vault-as-secret-store/) to set up vault as external secret store.

I have the following `XRD`, `Composition` and `Claim` resources:

<details>
<summary>`XRD` yaml:</summary>

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xcruiseserviceaccounts.getcruise.com
spec:
  group: getcruise.com
  names:
    kind: XCruiseServiceAccount
    plural: xcruiseserviceaccounts
  claimNames:
    kind: CruiseServiceAccount
    plural: cruiseserviceaccounts
  connectionSecretKeys:
    - key.json
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec: {}
```
</details>

<details>
<summary>`Composition` yaml:</summary>

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xcruiseserviceaccounts.getcruise.com
  labels:
    provider: gcp
spec:
  publishConnectionDetailsWithStoreConfigRef:
    name: vault
  compositeTypeRef:
    apiVersion: getcruise.com/v1alpha1
    kind: XCruiseServiceAccount
  resources:
    - name: serviceaccount
      base:
        # https://doc.crds.dev/github.com/upbound/provider-gcp/cloudplatform.gcp.upbound.io/ServiceAccount/v1beta1
        apiVersion: cloudplatform.gcp.upbound.io/v1beta1
        kind: ServiceAccount
        spec:
          forProvider: {}
      patches:
        - type: CombineFromComposite
          toFieldPath: spec.forProvider.description
          policy:
            fromFieldPath: Required
          combine:
            variables:
              - fromFieldPath: spec.claimRef.namespace
              - fromFieldPath: spec.claimRef.name
            strategy: string
            string:
              fmt: "%s/%s"
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.email
          toFieldPath: status.serviceAccountEmail
          policy:
            fromFieldPath: Required
    - name: serviceaccountkey
      base:
        # https://doc.crds.dev/github.com/upbound/provider-gcp/cloudplatform.gcp.upbound.io/ServiceAccountKey/v1beta1
        apiVersion: cloudplatform.gcp.upbound.io/v1beta1
        kind: ServiceAccountKey
        spec:
          forProvider:
            publicKeyType: TYPE_X509_PEM_FILE
            serviceAccountIdSelector:
              matchControllerRef: true
          publishConnectionDetailsTo:
            configRef:
              name: vault
      patches:
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: metadata.uid
            strategy: string
            string:
              fmt: "%s-serviceaccountkey"
          toFieldPath: spec.publishConnectionDetailsTo.name
          policy:
            fromFieldPath: Required
      connectionDetails:
        - fromConnectionSecretKey: private_key
          name: key.json
```
</details>

<details>
<summary>`Claim` yaml:</summary>

```yaml
apiVersion: getcruise.com/v1alpha1
kind: CruiseServiceAccount
metadata:
  name: jonnys-sa
spec:
  publishConnectionDetailsTo:
    configRef:
      name: vault
    name: jonnys-sa
```
</details>

These are the `storeConfigs` the above configs are referring to:

<details>
<summary>`storeconfigs.gcp.upbound.io` yaml:</summary>

```yaml
apiVersion: gcp.upbound.io/v1alpha1
kind: StoreConfig
metadata:
  name: vault
spec:
  defaultScope: crossplane
  type: Vault
  vault:
    auth:
      method: Token
      token:
        fs:
          path: /vault/secrets/token
        source: Filesystem
    mountPath: secret/gcp
    server: https://vault.server:8200
    version: v1
```
</details>

<details>
<summary>`storeconfigs.secrets.crossplane.io` yaml:</summary>

```yaml
apiVersion: secrets.crossplane.io/v1alpha1
kind: StoreConfig
metadata:
  name: vault
spec:
  defaultScope: crossplane
  type: Vault
  vault:
    auth:
      method: Token
      token:
        fs:
          path: /vault/secrets/token
        source: Filesystem
    mountPath: secret/crossplane
    server: https://vault.server:8200
    version: v1
```
</details>

### What happened?
When applying the claim with the above config, the user visible secret at vault path `secret/crossplane/my-namespace/jonnys-sa` gets written, but it doesn't have the most important `key.json` field:
```
╰─ vault read secret/crossplane/my-namespace/jonnys-sa
Key                                        Value
---                                        -----
refresh_interval                           20h
metadata:secret.crossplane.io/owner-uid    a8aecac9-4cdc-4a96-b1ef-2569ebee3337
```

Also the composite secret (which is stored in the `crossplane` scope) has no value:
```
╰─ vault read secret/crossplane/crossplane/1eebda12-373b-4b8c-9de1-e5cdbcc0f8f6
Key                                        Value
---                                        -----
refresh_interval                           20h
metadata:secret.crossplane.io/owner-uid    1eebda12-373b-4b8c-9de1-e5cdbcc0f8f6
```

However, the manged resource has the correct value with all the keys exposed by the underlying provider resource:
```
╰─ vault read secret/paas/crossplane/dev/gcp/crossplane/a293b4ae-67d4-4c48-b397-1fc7a14e7778-serviceaccountkey
Key                                        Value
---                                        -----
refresh_interval                           20h
attribute.private_key                      <base 64 of private key>
metadata:secret.crossplane.io/owner-uid    5dd95ff4-4fc4-4f1e-840d-c25f3a503078
private_key                                {
  "type": "service_account",
  "project_id": "<project id>",
  "private_key_id": "<private key id>",
  "private_key": "<private-key-pem>",
  "client_email": "jonnys-sa-r4hpq-qvw7j@<project id>.iam.gserviceaccount.com",
  "client_id": "<client id>",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "<url>"
}
```

The latter, the managed resource secret is expected, but we would also expect the composite and the claim secret in vault.

### How can this be improved?
Our current workaround is to store the managed resource secret and the composite resource secret as kubernetes secret and then only store the claim secret in vault, which works.
We do that by changing the `publishConnectionDetailsWithStorageConfigRef` from `vault` to `default` on the composition:
```
  publishConnectionDetailsWithStoreConfigRef:
    name: default
```

However, we would like to even store the composite and the managed resource secrets in vault.

I classified this as bug as it's somewhat unexpected that if all secrets are stored in vault, they don't get propagated. There is also no error message in the debug logs of either the crossplane or the gcp operator.

### What environment did it happen in?
Crossplane version: `v1.10.1`
GCP provider version: `v0.27.0`

**Comment by jbw976** [comment] 2023-03-07 01:55
@ezgidemirel @turkenh, is this something that is getting addressed with the move to pluggable secret stores? https://github.com/crossplane/crossplane/issues/3670

**Comment by turkenh** [comment] 2023-03-07 06:58
> @ezgidemirel @turkenh, is this something that is getting addressed with the move to pluggable secret stores? #3670

@jbw976 this looks like a bug, indeed. 
It is great that @jonnylangefeld provided reproduction steps, so we can try to reproduce and see what is wrong.

**Comment by ezgidemirel** [comment] 2023-04-18 13:49
Hello @jonnylangefeld, I couldn't reproduce the issue. As you can see below, both claim's and composite's connection details are written to the Vault.

```
$ vault kv get secret/crossplane-system/jonnys-sa
============= Secret Path =============
secret/data/crossplane-system/jonnys-sa

======= Metadata =======
Key                Value
---                -----
created_time       2023-04-18T11:41:47.71163734Z
custom_metadata    map[secret.crossplane.io/owner-uid:b67f5265-30a8-40bf-b824-2451b592032b]
deletion_time      n/a
destroyed          false
version            1

====== Data ======
Key         Value
---         -----
key.json    {
  "type": "service_account",
  "project_id": "<project id>",
  "private_key_id": "<private key id>",
  "private_key": "<private key>,
  "client_email": "jonnys-sa-ffw48-8kk55@<project id>.iam.gserviceaccount.com",
  "client_id": "<client id>",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "<url>"
}
```
```
$ vault kv get secret/crossplane-system/210c13d9-5519-4a1f-b62f-57ff3e7afb49
=========================== Secret Path ===========================
secret/data/crossplane-system/210c13d9-5519-4a1f-b62f-57ff3e7afb49

======= Metadata =======
Key                Value
---                -----
created_time       2023-04-18T11:41:44.187618838Z
custom_metadata    map[secret.crossplane.io/owner-uid:210c13d9-5519-4a1f-b62f-57ff3e7afb49]
deletion_time      n/a
destroyed          false
version            1

====== Data ======
Key         Value
---         -----
key.json    {
  "type": "service_account",
  "project_id": "<project id>",
  "private_key_id": "<private key id>",
  "private_key": "<private key>",
  "client_email": "jonnys-sa-ffw48-8kk55@<project id>.iam.gserviceaccount.com",
  "client_id": "<client id>",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "<url>"
}
```

I suspect that one of the storeconfig resources (the one for crossplane configuration) was not created. Could you please try again?

**Comment by jeanduplessis** [comment] 2023-05-24 09:00
Closing issue for now since it could not be reproduced, feel free to add any additional info for us to look into.

**Closed by jeanduplessis** 2023-05-24 09:00 UTC
Labels: bug, secret-stores
