### ISSUE TITLE
Smaller provider that contains config resources is reinstalled after deletion

### ISSUE THREAD

**Issue by ezgidemirel** [crossplane/crossplane#4063] opened 2023-05-10 11:44 UTC
### What happened?

After installing a smaller provider, the config provider is installed automatically as a dependency. Once I delete both of these smaller providers, the config provider is reinstalled and I needed to delete it one more time. 

### How can we reproduce it?

You can install any smaller provider and delete it. 

### What environment did it happen in?
Crossplane version: v1.12.1

**Comment by turkenh** [comment] 2023-05-11 08:01
I believe this is because dependencies are defined to the `ProviderRevisions` / `ConfigurationRevisions` rather than `Providers` / `Configurations`. 

So, even if we delete the Configuration package, `ConfigurationRevisions` are still around for a while (until cleanup is completed) and their dependencies are re-deployed if we had deleted them manually. I assume it would not be an issue if we delete dependencies after ConfigurationRevisions got deleted.

**Comment by turkenh** [comment] 2023-07-26 07:24
Closing this it works as designed, as stated above.

**Closed by turkenh** 2023-07-26 07:24 UTC
Labels: bug, package
