### ISSUE TITLE
KubernetesApplication does not get update when KubernetesApplicationResources change

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1134] opened 2019-12-23 13:48 UTC
### What problem are you facing?

I have an app stack which uses `KubernetesApplication`. I get the endpoint of my application through `KubernetesApplication -> KubernetesApplicationResource.remote.Service` resource in my controller. However, since `KubernetesApplication` doesn't get any update when the `KubernetesApplicationResource`s it deployed changes, I have to rely on periodic checks instead of getting an event instantly and processing it.

### How could Crossplane help solve your problem?

`KubernetesApplicationResource` could have a specific `condition` for high level status reporting like `creating`, `ready`(specific to template kind, like `replicas == readyReplicas` for deployment), `deleting`. `KubernetesApplication` controller can look at and report one merged condition on owner `KubernetesApplication`. This way if any high level changes happen in one of the children `KubernetesApplicationResource`, `KubernetesApplication` would get updated and other controllers who watch it can get an update event.

**Comment by negz** [comment] 2020-01-09 01:44
Two things to consider here:

* KubernetesApplication is a set of templates for the specs of KubernetesApplicationResources. It's by design that we don't back-propagate updates to those KARs once they've been instantiated.
* Handling the status of a KubernetesApplicationResource is difficult because we have no concept of what "ready" is for the resources they template (i.e. a KAR could represent a Deployment, an Ingress, or a CRD, all of which represent readiness differently). One option here might be to use some of the fieldpath derived readiness rules we've thought about for template stacks etc. i.e. "If this field has this value, then the thing is ready".

**Comment by muvaf** [comment] 2020-01-10 14:35
I agree it's difficult to report readiness of arbitrary resources.

I'm actually starting to think that this may not be necessary, my problem is that the thing is not event-based, meaning KA is not updated to send me a reconcile request even though KARs got updated and KA was reconciled. So, even something like a `condition` on `KA.status` that is refreshed in each reconcile of KA would do the job of signaling the stack controller that something is changed.

**Comment by negz** [comment] 2020-06-30 02:16
We're planning to remove support for KubernetesApplication, so I think we can close this.

**Closed by negz** 2020-06-30 02:16 UTC
Labels: enhancement
