### ISSUE TITLE
crossplane init-container error after re-install crossplane

### ISSUE THREAD

**Issue by romulobil** [crossplane/crossplane#4066] opened 2023-05-10 15:21 UTC
### What happened?
I unistall crossplane version v1.12 because I couldn't remove managed resources. 
So, I re-install the same stable version, but init-container from crossplane POD got this error:

NAME                                                                    READY   STATUS       RESTARTS      AGE
crossplane-cb755467b-lhkj7                              0/1     Init:Error       1 (13s ago)   21s                                                                                                                   
crossplane-rbac-manager-69ff585d75-t5zdj   1/1     Running       0                     21s

$kubectl logs crossplane-cb755467b-lhkj7
Defaulted container "crossplane" out of: crossplane, crossplane-init (init)
Error from server (BadRequest): container "crossplane" in pod "crossplane-cb755467b-lhkj7" is waiting to start: PodInitializing

I have read this older bug https://github.com/crossplane/crossplane/issues/2840 , similar to that, but I didn't understand what was made to be resolved

I am using kubernetes client 1.24.3 and server v1.22.17-eks-48e63af

**Comment by romulobil** [comment] 2023-05-10 15:40
After a new uninstall e re-install using the latest stable version from helm, it's ok

$ helm install crossplane crossplane-stable/crossplane --namespace crossplane-system 
NAME: crossplane
LAST DEPLOYED: Wed May 10 12:23:03 2023
NAMESPACE: crossplane-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Release: crossplane

Chart Name: crossplane
Chart Description: Crossplane is an open source Kubernetes add-on that enables platform teams to assemble infrastructure from multiple vendors, and expose higher level self-service APIs for application teams to consume.
Chart Version: 1.10.1
Chart Application Version: 1.10.1

Kube Version: v1.22.17-eks-48e63af


$ kubectl get pods
NAME                                                                        READY   STATUS    RESTARTS   AGE
crossplane-cb755467b-rqjpj                                  1/1         Running   0                12m
crossplane-rbac-manager-69ff585d75-d2j4m   1/1         Running   0                 12m

**Comment by negz** [comment] 2023-05-10 21:25
Unfortunately this isn't enough information to figure out what happened here. It looks to me like:

* The problem was with the init container (`crossplane-init`)
* You checked the logs of the pod, which defaulted to the main container (`crossplane`, not `crossplane-init`)

So we can't tell what was preventing `crossplane-init` from starting, sorry.

Given you have this working I'm going to close this issue. Please let us know if you can reproduce this.

**Closed by negz** 2023-05-10 21:25 UTC
Labels: bug
