### ISSUE TITLE
XR referencing wrong StoreConfig?

### ISSUE THREAD

**Issue by jaylevin** [crossplane/crossplane#4171] opened 2023-06-12 16:30 UTC
#### Given:

1. `StoreConfig.secrets.crossplane.io` with `metadata.name: vault-core`
    a. Composition with `publishConnectionDetailsWithStoreConfigRef.name` equal to  `vault-core`
    b. XRC with `publishConnectionDetailsTo.configRef.name` equal to `vault-core`
2. `StoreConfig.confluent.customgroup.io` with `metadata.name` `vault-confluent`
    a. MR with `publishConnectionDetailsTo.configRef.name` equal to `vault-confluent`

#### Expected behavior:
1. MR Connection secrets are created with `vault-confluent` and propagated up to XRC/XR, which uses the `vault-core` StoreConfig.

#### Observed behavior:
```log
cannot compose resources: cannot get existing composed resources: cannot fetch connection details for composed resource "api-key" 
(a APIKey named api-key): cannot connect to secret store: cannot get store config: StoreConfig.secrets.crossplane.io "vault-confluent" not found
```
It appears that Crossplane is trying to generate the XR connection secret with the `StoreConfig.secrets.crossplane.io/vault-confluent`, but that StoreConfig only exists at the `StoreConfig.confluent.customgroup.io` api group.

### How can we reproduce it?

See the "Given" section specified above for steps to reproduce.

### What environment did it happen in?
Crossplane version: v1.11.3

**Comment by turkenh** [comment] 2023-07-12 08:22
Given that we couldn't reproduce the issue, I am closing it. 

@jaylevin feel free to open with more details if this is still an issue for you.

**Closed by turkenh** 2023-07-12 08:22 UTC
Labels: bug, secret-stores
