### ISSUE TITLE
Secrets not populated for composite resources

### ISSUE THREAD

**Issue by mf-lit** [crossplane/crossplane#2253] opened 2021-04-08 16:11 UTC
I'm having trouble getting secrets to populate for a composite resource and can't see why. This particular XR is for SQS queues, we have other XRs (for IAM and RDS for example) that have no problem with this. (So I guess this might be an issue with the provider not crossplane-core, but opening it here since I'm unsure).

<details>
<summary><code>claim</code></summary>

```yaml
apiVersion: platform.example.com/v1alpha1
kind: ZaapQueue
metadata:
  name: mftest
spec:
  parameters:
    deletionPolicy: Delete
    tags:
      managed_by: crossplane
      service_name: mftest
  writeConnectionSecretToRef:
    name: mftest-queue
```

</details>

<details>
<summary><code>XRD</code></summary>

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: zaapqueuecomposites.platform.example.com
spec:
  claimNames:
    kind: ZaapQueue
    plural: zaapqueues
  connectionSecretKeys:
  - endpoint
  defaultCompositionRef:
    name: zaapqueuecomposite
  group: platform.example.com
  names:
    kind: ZaapQueueComposite
    plural: zaapqueuecomposites
  versions:
  - name: v1alpha1
    referenceable: true
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              parameters:
                properties:
                  deletionPolicy:
                    description: Delete or Orphan resource on deletion
                    type: string
                  kmsMasterKeyId:
                    description: KMS Key Alias
                    type: string
                  region:
                    description: Region for queue
                    type: string
                  tags:
                    additionalProperties:
                      type: string
                    description: AWS resource tags
                    type: object
                type: object
            required:
            - parameters
            type: object
        type: object
    served: true

```

</details>

<details>
<summary><code>composition</code></summary>

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: zaapqueuecomposite
spec:
  compositeTypeRef:
    apiVersion: platform.example.com/v1alpha1
    kind: ZaapQueueComposite
  patchSets:
  - name: Metadata
    patches:
    - fromFieldPath: metadata.labels
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.annotations
      type: FromCompositeFieldPath
  resources:
  - base:
      apiVersion: sqs.aws.crossplane.io/v1beta1
      kind: Queue
      spec:
        deletionPolicy: Orphan
        forProvider:
          kmsMasterKeyId: alias/aws/sqs
          region: eu-west-1
          tags:
            managed_by: crossplane
        providerConfigRef:
          name: crossplane-provider-aws
        writeConnectionSecretToRef:
          namespace: crossplane
    connectionDetails:
    - fromConnectionSecretKey: endpoint
    patches:
    - patchSetName: Metadata
      type: PatchSet
    - fromFieldPath: spec.parameters.tags
      toFieldPath: spec.forProvider.tags
      type: FromCompositeFieldPath
    - fromFieldPath: spec.parameters.region
      toFieldPath: spec.forProvider.region
      type: FromCompositeFieldPath
    - fromFieldPath: spec.parameters.kmsMasterKeyId
      toFieldPath: spec.forProvider.kmsMasterKeyId
      type: FromCompositeFieldPath
    - fromFieldPath: spec.parameters.deletionPolicy
      toFieldPath: spec.deletionPolicy
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.uid
      toFieldPath: spec.writeConnectionSecretToRef.name
      transforms:
      - string:
          fmt: '%s-queue'
        type: string
      type: FromCompositeFieldPath
  writeConnectionSecretsToNamespace: crossplane
```
</details>

### What happened?

When the claim is created, a XR and MR are created as expected. A secret is created for the MR too:
```
$ kubectl get zaapqueue | grep mftest
mftest       True    mftest-queue       
$ kubectl get zaapqueuecomposites.platform.example.com | grep mftest
mftest-2l4ck       True    zaapqueuecomposite   10m
$ kubectl get queue | grep mftest
mftest-2l4ck-rn4wr       arn:aws:sqs:eu-west-1:11111111111111:mftest-2l4ck-rn4wr   True    True     18m
$ kubectl get secret -n crossplane | grep queue
4d442ec9-18d9-4e99-8e3e-7a6a0ea269e2-queue         connection.crossplane.io/v1alpha1     1      10m
```

Further, a secret is created for the XR and the claim but both these secrets have no data
```
$ kubectl get secret | grep mftest
mftest-queue                        connection.crossplane.io/v1alpha1     0      
$ kubectl get secret -n crossplane | grep 4d442ec9-18d9-4e99-8e3e-7a6a0ea269e2
4d442ec9-18d9-4e99-8e3e-7a6a0ea269e2               connection.crossplane.io/v1alpha1     0      13m
4d442ec9-18d9-4e99-8e3e-7a6a0ea269e2-queue         connection.crossplane.io/v1alpha1     1      13m  
```

Finally, here's the description of the composite resource:

<details>
<summary><code>kubectl describe zaapqueuecomposites.platform.example.com mftest-2l4ck</code></summary>

```yaml
Name:         mftest-2l4ck 
Namespace:
Labels:       crossplane.io/claim-name=mftest
              crossplane.io/claim-namespace=example
              crossplane.io/composite=mftest-2l4ck
Annotations:  crossplane.io/external-name:
API Version:  platform.example.com/v1alpha1
Kind:         ZaapQueueComposite
Metadata:
  Creation Timestamp:  2021-04-08T15:48:55Z
  Generate Name:       mftest-
  Generation:          5
    Manager:         crossplane
    Operation:       Update
    Time:            2021-04-08T15:48:56Z
  Resource Version:  23982666
  Self Link:         /apis/platform.example.com/v1alpha1/zaapqueuecomposites/mftest-2l4ck
  UID:               4d442ec9-18d9-4e99-8e3e-7a6a0ea269e2
Spec:
  Claim Ref:
    API Version:  platform.example.com/v1alpha1
    Kind:         ZaapQueue
    Name:         mftest
    Namespace:    example
  Composition Ref:
    Name:  zaapqueuecomposite
  Parameters:
    Deletion Policy:  Delete
    Tags:
      managed_by:    crossplane
      service_name:  mftest
  Resource Refs:
    API Version:  sqs.aws.crossplane.io/v1beta1
    Kind:         Queue
    Name:         mftest-2l4ck-rn4wr
  Write Connection Secret To Ref:
    Name:       4d442ec9-18d9-4e99-8e3e-7a6a0ea269e2
    Namespace:  crossplane
Status:
  Conditions:
    Last Transition Time:  2021-04-08T15:48:56Z
    Reason:                Creating
    Status:                False
    Type:                  Ready
  Connection Details:
    Last Published Time:  2021-04-08T15:48:56Z
Events:
  Type     Reason                   Age                From                                                             Message
  ----     ------                   ----               ----                                                             -------
  Normal   CompositionSelection     30s                defined/compositeresourcedefinition.apiextensions.crossplane.io  Default composition has been selected
  Warning  ComposeResources         30s (x2 over 30s)  defined/compositeresourcedefinition.apiextensions.crossplane.io  Operation cannot be fulfilled on zaapqueuecomposites.platform.example.com "mftest-2l4ck": the object has been modified; please apply your changes to the latest version and try again
  Normal   SelectComposition        29s (x4 over 30s)  defined/compositeresourcedefinition.apiextensions.crossplane.io  Successfully selected composition
  Normal   ComposeResources         29s (x2 over 29s)  defined/compositeresourcedefinition.apiextensions.crossplane.io  Successfully composed resources
  Normal   PublishConnectionSecret  29s                defined/compositeresourcedefinition.apiextensions.crossplane.io  Successfully published connection details
```
</details>

### What environment did it happen in?
Crossplane version: 1.1
AWS Provider: 0.18-rc0
Kubernetes: 1.19 (EKS)

**Comment by negz** [comment] 2021-04-09 00:08
Hrm, it certainly seems like your configuration is all correct. I see that:

1. Your XRD declares that it writes the `endpoint` connection secret key.
2. Your Composition sets `endpoint` from the SQS queue's `endpoint` key.
3. The SQS queue appears to set an `endpoint` key.

Is the SQS queue secret definitely writing the `endpoint` key and not some other (I see that there's one data entry set). If it is, this is almost certainly an issue with Crossplane core (or some subtle misconfiguration I'm not spotting?).

**Comment by mf-lit** [comment] 2021-04-09 08:20
Thanks for taking the time to review my config @negz , I was sure it must have been something I'd done.

To answer your question, the endpoint key is definitely there.

If I can provide any further debugging info, let me know.

```
describe secret -n crossplane 4d442ec9-18d9-4e99-8e3e-7a6a0ea269e2-queue
Name:         4d442ec9-18d9-4e99-8e3e-7a6a0ea269e2-queue
Namespace:    crossplane
Labels:       <none>
Annotations:  <none>

Type:  connection.crossplane.io/v1alpha1

Data
====
endpoint:  69 bytes
```

**Comment by muvaf** [comment] 2022-04-22 00:31
Is this duplicate of https://github.com/crossplane/crossplane/issues/2417 ?

**Closed by muvaf** 2022-04-22 00:31 UTC
Labels: bug, composition
