### ISSUE TITLE
Silent failure from composition when child resource spec is invalid

### ISSUE THREAD

**Issue by amanfredi** [crossplane/crossplane#4689] opened 2023-09-26 19:32 UTC
### What happened?

I have been working on creating a Composition involving several resources from the AWS provider. The behavior I'm seeing is that if the spec of one of my sub-resources is structurally invalid, the composition fails to render but with no error events produced.

For example, I tried to create a Route53 Record with the following syntax:
```
apiVersion: route53.aws.upbound.io/v1beta1
kind: Record
metadata:
  name: test-record
spec:
  providerConfigRef:
    name: my-provider-config
  forProvider:
    alias:
      evaluateTargetHealth: false
      name: some-domain.cloudfront.net
      zoneId: Z2FDTNDATAQYW2 # magic zoneId for alias to CloudFront Distributions
    name: test-1
    type: A
    zoneIdRef:
      name: example.io
    region: us-east-1
```
This is invalid because per the Record spec, `alias` is expected to be an array and not an object.
When applying the yaml with kubectl, you receive the following error:
```Error from server (BadRequest): error when creating "test-record.yaml": Record in version "v1beta1" cannot be handled as a Record: strict decoding error: unknown field "spec.forProvider.alias.evaluateTargetHealth", unknown field "spec.forProvider.alias.name", unknown field "spec.forProvider.alias.zoneId"```

However, when created as part of a Composition, the creation of the Record fails silently, and the Composite Resource never becomes ready.

### What environment did it happen in?
Crossplane version: 1.13
upbound/provider-family-aws v0.40.0

**Comment by turkenh** [comment] 2023-10-02 10:53
@amanfredi thanks for the report. I could reproduce this with `v1.13.2` but not on the latest master, indicating that this has been resolved with one of the latest improvements in the composition engine.

Here is what I see with the latest master:

```bash
# Install latest master
helm repo add crossplane-master https://charts.crossplane.io/master --force-update
helm upgrade --install crossplane --namespace crossplane-system crossplane-master/crossplane --version v1.14.0-rc.0.392.g53f713cd --create-namespace

...

kubectl describe composite

...
Status:
  Conditions:
    Last Transition Time:  2023-10-02T10:45:00Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
    Last Transition Time:  2023-10-02T10:45:13Z
    Message:               Unready resources: repro-resource
    Reason:                Creating
    Status:                False
    Type:                  Ready

Events:
  Type     Reason                   Age                  From                                                             Message
  ----     ------                   ----                 ----                                                             -------
  Normal   CompositionUpdatePolicy  2m                   defined/compositeresourcedefinition.apiextensions.crossplane.io  Default composition update policy has been selected
  Normal   SelectComposition        2m                   defined/compositeresourcedefinition.apiextensions.crossplane.io  Successfully selected composition: xnopresources.nop.example.org
  Normal   SelectComposition        2m                   defined/compositeresourcedefinition.apiextensions.crossplane.io  Selected composition revision: %!s(MISSING)
  Warning  ComposeResources         119s                 defined/compositeresourcedefinition.apiextensions.crossplane.io  cannot dry-run apply composed resource "repro-resource": cannot use dry-run create to name composed resource: Record.route53.aws.upbound.io "apiextensions-composition-pandt-lzlzk-r4vdm" is invalid: [spec.forProvider.alias: Invalid value: "object": spec.forProvider.alias in body must be of type array: "object", <nil>: Invalid value: "null": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation]
  Warning  ComposeResources         119s                 defined/compositeresourcedefinition.apiextensions.crossplane.io  cannot dry-run apply composed resource "repro-resource": cannot use dry-run create to name composed resource: Record.route53.aws.upbound.io "apiextensions-composition-pandt-lzlzk-xjpr7" is invalid: [spec.forProvider.alias: Invalid value: "object": spec.forProvider.alias in body must be of type array: "object", <nil>: Invalid value: "null": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation]
```

So, I am closing this as fixed!

P.S.: There is a minor issue introduced due to this which is, we are now seeing a growing list of events since event messages are not unique (no the generated name of the resource), which I will follow up with a separate ticket.

**Closed by turkenh** 2023-10-02 10:53 UTC
Labels: bug
