### ISSUE TITLE
helm install is not working.

### ISSUE THREAD

**Issue by bshetti** [crossplane/crossplane#1064] opened 2019-11-14 08:12 UTC
### What happened?
Using helm 3 and ran 
helm install crossplane crossplane-alpha/crossplane --namespace crossplane-system

we get
NAMESPACE           NAME                                                        READY     STATUS             RESTARTS   AGE
crossplane-system   crossplane-cd67688d6-2flrh                                  1/1       Running            0          17s
crossplane-system   crossplane-stack-manager-564bcb979-rj9mg                    0/1       CrashLoopBackOff   1          17s

Here is the LOG info for the pod that is crossplane-stack-manager:

```bash
ubuntu@ip-172-31-9-213:~$ kubectl logs crossplane-stack-manager-564bcb979-rj9mg -n crossplane-system
2019-11-14T08:07:50.718Z	INFO	crossplane	Sync period	{"duration": "1h0m0s"}
2019-11-14T08:07:51.264Z	INFO	controller-runtime.metrics	metrics server is starting to listen	{"addr": ":8080"}
2019-11-14T08:07:51.265Z	INFO	crossplane	Adding schemes
2019-11-14T08:07:51.266Z	INFO	crossplane	Adding controllers
2019-11-14T08:07:51.269Z	INFO	controller-runtime.controller	Starting EventSource	{"controller": "stackinstall.stacks.crossplane.io", "source": "kind source: /, Kind="}
2019-11-14T08:07:51.269Z	ERROR	controller-runtime.source	if kind is a CRD, it should be installed before calling Start	{"kind": "StackInstall.stacks.crossplane.io", "error": "no matches for kind \"StackInstall\" in version \"stacks.crossplane.io/v1alpha1\""}
github.com/go-logr/zapr.(*zapLogger).Error
	/home/upbound/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start
	/home/upbound/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/source/source.go:88
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Watch
	/home/upbound/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:122
sigs.k8s.io/controller-runtime/pkg/builder.(*Builder).doWatch
	/home/upbound/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/builder/controller.go:162
sigs.k8s.io/controller-runtime/pkg/builder.(*Builder).Build
	/home/upbound/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/builder/controller.go:151
sigs.k8s.io/controller-runtime/pkg/builder.(*Builder).Complete
	/home/upbound/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/builder/controller.go:129
github.com/crossplaneio/crossplane/pkg/controller/stacks/install.(*Controller).SetupWithManager
	/home/upbound/go/src/github.com/crossplaneio/crossplane/pkg/controller/stacks/install/stackinstall.go:89
github.com/crossplaneio/crossplane/pkg/controller/stacks.(*Controllers).SetupWithManager
	/home/upbound/go/src/github.com/crossplaneio/crossplane/pkg/controller/stacks/stacks.go:39
main.stacksControllerSetupWithManager
	/home/upbound/go/src/github.com/crossplaneio/crossplane/cmd/crossplane/main.go:153
main.main
	/home/upbound/go/src/github.com/crossplaneio/crossplane/cmd/crossplane/main.go:134
runtime.main
	/usr/local/go/src/runtime/proc.go:200
crossplane: error: Cannot add controllers to manager: no matches for kind "StackInstall" in version "stacks.crossplane.io/v1alpha1"
```

### How can we reproduce it?
Just follow your instructions for helm

### What environment did it happen in?
Crossplane version:

**Comment by soorena776** [comment] 2019-11-14 14:53
Duplicate of #1062

**Comment by displague** [comment] 2019-11-14 15:24
Thanks for reporting this, @bshetti.  We've encountered this problem with [Helm 3](https://github.com/helm/helm/releases/tag/v3.0.0), which was released yesterday :tada:, and this should be addressed in v0.6 unless we can get a fix in for this today/tomorrow.

**Comment by turkenh** [comment] 2019-11-14 16:26
@bshetti  as a workaround you can manually create the missing two crds as follows before installing the chart:

```
kubectl apply -f https://raw.githubusercontent.com/crossplaneio/crossplane/release-0.4/cluster/charts/crossplane/templates/crds/stacks.crossplane.io_stackinstalls.yaml
kubectl apply -f https://raw.githubusercontent.com/crossplaneio/crossplane/release-0.4/cluster/charts/crossplane/templates/crds/stacks.crossplane.io_clusterstackinstalls.yaml
```

It can help after `helm install` as well, but you may need to restart stack manager pod to speed up things.

```
kubectl rollout restart deploy crossplane-stack-manager -n crossplane-system
```

**Comment by bshetti** [comment] 2019-11-14 17:37
Thank you. Apologies for replicating. It was a late night, and I surely missed the replica. I will try in a bit today. Thanks

**Comment by displague** [comment] 2020-01-09 23:04
Have you had a chance to try this again @bshetti ?

**Comment by negz** [comment] 2020-06-30 01:53
We haven't heard from you in a while @bshetti, so I'm going to close this issue. Let us know if we should reopen it!

**Closed by negz** 2020-06-30 01:53 UTC
Labels: bug
