### ISSUE TITLE
packagePullSecrets not working on v1.6.2

### ISSUE THREAD

**Issue by fahedouch** [crossplane/crossplane#2876] opened 2022-02-03 14:19 UTC
### What happened?

`401 authorization required` on private registry when using the latest stable version `v1.6.2` 

it works with `v1.6.1` 
### How can we reproduce it?

```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: test
spec:
  package: "eu.gcr.io/xxx"
  packagePullPolicy: Always
  packagePullSecrets:
    - name: gcr-json-key
  ```
### What environment did it happen in?
Crossplane version:  v1.6.2

**Comment by hasheddan** [comment] 2022-02-03 14:55
@fahedouch thank you for raising this! I am investigating 👍🏻

**Comment by hasheddan** [comment] 2022-02-03 16:53
@fahedouch I tested out pulling a private package from `gcr` using a [JSON key file](https://cloud.google.com/container-registry/docs/advanced-authentication#json-key), which appears to be the flow you used here and was able to verify that with the package pull secret it was successful and without it was not. Can you verify that the `Secret` with name `gcr-json-key` in the `crossplane-system` namespace is indeed valid for pull the image in question?

**Comment by fahedouch** [comment] 2022-02-08 08:50
@hasheddan , thank you for checking this. did you use the `v1.6.2` ?

still have the same error with `v1.6.2` : 
```
Events:
  Type     Reason         Age              From                                 Message
  ----     ------         ----             ----                                 -------
  Warning  UnpackPackage  3s (x3 over 4s)  packages/provider.pkg.crossplane.io  cannot unpack package: failed to fetch package digest from remote: HEAD https://eu.gcr.io/xxxxx/manifests/v0.2.0-110.g588be75: unexpected status code 401 Unauthorized (HEAD responses have no body, use GET for details)
```

but it is ok with `v1.6.1` 

I am using `.dockerconfigjson`  json secret

**Comment by hasheddan** [comment] 2022-02-08 11:21
@fahedouch hmm yes I did try with v1.6.2. What is the GCR entry in your dockerconfig using for credential resolution for `eu.gcr.io`?

**Comment by hasheddan** [comment] 2022-02-09 00:04
@fahedouch my apologies, I have repeated the steps and now am able to reproduce. I believe we should be falling through to the [pull secret auth](https://github.com/google/go-containerregistry/blob/d3202cccdc39e7435cd37c8d002ff6ad599cb1c1/pkg/authn/kubernetes/keychain.go#L138) since the [others in the chain](https://github.com/google/go-containerregistry/blob/d3202cccdc39e7435cd37c8d002ff6ad599cb1c1/pkg/authn/k8schain/k8schain.go) should not give you anything more than `anonymous` creds. However, I haven't been able to determine the exact behavior yet. I'll make sure to keep you updated as I work on getting a fix in place 👍🏻

**Comment by hasheddan** [comment] 2022-02-14 14:23
@fahedouch following up here -- was able to do some experiments this morning and it may be the case that because the default and gcloud resolvers come [earlier in the chain](https://github.com/google/go-containerregistry/blob/41f8d92709b7d7c96a210f2652f2862314f5ba7f/pkg/authn/k8schain/k8schain.go#L48), one is getting resolved first, but with credentials that are not valid for the image being pulled. Because it resolves, we never get to the package pull secrets. Do you have any additional information about the environment you are running Crossplane in?

**Comment by mcbenjemaa** [comment] 2022-03-04 13:49
My team is blocked, we are trying to move from DTR to artifact-registry.

**Comment by hasheddan** [comment] 2022-03-04 13:54
@mcbenjemaa I believe this may have been fixed in https://github.com/google/go-containerregistry/issues/1298 -- I will coordinate with you to test an update in your environment 👍🏻

**Closed** 2022-03-04 23:52 UTC
Labels: bug
