### ISSUE TITLE
Errors should explicitly recommend inspecting child resources

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#4078] opened 2023-05-16 23:24 UTC
### What problem are you facing?

Many Crossplane concepts involve layers of API abstractions. For example:

* Claim -> XR -> MRs
* Provider - > ProviderRevision

When Crossplane encounters an error, our approach is to provide as much detail about the error _at the level it occurred_, then summarize at higher levels of abstraction. For example if an MR can't be created I'd expect to see something like:

* MR: A status condition and event explaining why the MR can't be created.
* XR: A status condition and event explaining that the XR cannot compose resources
* Claim: A status condition and event explaining that the XR is not yet ready.

This is similar to the approach taken by in-tree Kubernetes controllers. For example when a Pod has failed, you must inspect the Pod to find out why. The Deployment just says something like "1 out of 2 Pods are ready".

While I believe we're doing the right thing by keeping the most detailed information aligned with the resource that's actually broken, this has been a frequent source of confusion (see for example https://github.com/crossplane/crossplane/issues/3262). I find myself frequently guiding folks to inspect (i.e. `kubectl describe`) "the next level down" to find out what's going on.

### How could Crossplane help solve your problem?

A lightweight change that may help here would be to update our error messages to explicitly recommend looking at the broken types. For example currently if a `Provider` is having issues you're likely to see an error like `current package revision health is unknown`. Perhaps this could be amended to also say something like `inspect ProviderRevisions for more information`.

**Comment by yhrn** [comment] 2023-05-22 16:49
Hi,

I started a Slack-thread [here](https://crossplane.slack.com/archives/CEG3T90A1/p1684244713020129) with some thoughts that relate to this. Quoting myself:

>  I find it a bit surprising that the idea is that application developers should need to drill down two levels into the MR to find out that they made a simple mistake.  I thought that the idea was that application developers (as opposed to platform developers) should only need to know about the claim and that the underlying composite resource and MR should be seen as internals of the platform. I mean, if I just wanted to create an S3 Bucket, why should I need to understand what a composite resource is and a managed resource, and a claim, and how they relate to each other? I just want a simple API where I can declare what I want and see the status of that thing.

I think it might make sense to keep some details in the MR status, especially if it relates to platform internal problems, but for "user errors" I really think they should be propagated to the claim. In some cases it might be possible to catch such errors via schema validation, but for many parameters it's not practical to keep this in the schema, e.g. what cloud provider regions, availability zones or machine types there are.

Furthermore, our use case as a platform team (and I think this is a common pattern) is that we provide GitOps support as well, and we want to automatically provide feedback about the result of applying a change to PRs and commits. Using tools like ArgoCD make it relatively easy to propagate information from the status of resources directly managed. But trying to automatically propagate the relevant status from one of the child resources, potentially two layers down, would be much trickier. Even more so if trying to avoid drowning the end user in irrelevant information.

**Comment by sttts** [comment] 2023-05-24 12:38
Another aspect: if the claim cluster is not the Crossplane cluster (via some binding e.g. through Upbound connector, kube-bind or some day in a kcp world), then the MRs are not even visible. So +1 to @yhrn's concern that in a platform-like environment with a persona split some kind of error propagation is needed. On the other hand, error propagation can also look like leaking of information. Hence, the holy grail here is about clever aggregation/abstraction of errors. That's hard.

**Comment by negz** [comment] 2023-05-25 00:28
Perhaps it would be useful to enumerate the kinds of errors we see and where we feel they should appear.

Here's a few things I can think of that would prevent a claim from becoming ready:

* A claim field value maps to an MR field value that is invalid according to the MR (CRD) schema. [^1]
* A claim field value maps to an MR field value that is invalid according to the external system (cloud provider).
* A claim uses a Composition that is somehow broken - e.g. attempting to compose a non-existent MR.
* A claim uses an MR that is somehow broken - e.g. provider doesn't have the credentials it needs to operate.

I'm sure there are plenty of others.

Now let me touch on how I see Crossplane's abstractions, and perhaps cloud abstractions in general. The quick version is I don't think developers can ignore how the sausage is made. I think the abstraction should leak.

In our context there's broadly two layers of sausage (poor analogy?):

1. Crossplane machinery. Claims, XRs, MRs, etc.
2. Cloud machinery. RDS, S3, etc.

I feel that abstractions like claims are a great way to lower the barrier to entry to a platform. As a developer starting out you don't need to know the details of how the sausage is made - you just make an API call based around the concepts your platform team presents to you. However once you start to stray from the happy path I think you need to know.

You probably need know about the cloud machinery - e.g. that a `VolvoBucket` is really an S3 bucket. It's hard to avoid that when writing code that consumes it. Wouldn't it be helpful to also know about the Crossplane machinery? How exactly Crossplane is turning a `VolvoBucket` into an S3 bucket? Sure, hopefully you don't need to be a Crossplane expert but it's probably useful for you to be able to discover via the control plane API that Crossplane in fact turned your `VolvoBucket` into an S3 bucket and an IAM role binding (or whatever). To go back to the Kubernetes analogy, I don't think application developers need to know how to run and configure a Kubernetes cluster but it's probably useful for them to be able to see that when they create a `Deployment`, Kubernetes is going to turn that into a couple of `Pod`s.

So, getting back to the things that could prevent a claim from becoming ready.

I do agree that it would be nice if we could figure out that when a cloud provider says `error 42: invalid widgets!` that means: 

1. `spec.forProvider.widgetCount` on a composed MR is wrong
2. `spec.forProvider.widgetCount` was in fact mapped from `spec.count` on the claim.
3. The claim author (app developer) should be told the `spec.count` they specified was wrong.
 
Unfortunately these mappings don't usually exist. The error the cloud provider returns to us often doesn't have the information we need to figure out which MR field was broken. Even at the claim -> MR level we don't currently "store" which MR fields were derived from which claim fields and how. Perhaps we could track and record that in some form of metadata, but I suspect accounting for transforms, functions, combine patches etc etc would make it challenging.

There's also often two parties involved with these errors. It's usually the application developer suffering from a mistake, but they're not always the one who caused it, and not always able to solve it. For example they could have specified a perfectly [cromulent](https://en.wiktionary.org/wiki/cromulent) field value, but one that triggers an unforeseen edge case in the selected `Composition`. I would expect this would require the platform team to fix the `Composition`.

So, I would still argue that taking all the various kinds of errors that might happen "below" the claim level and aggregating them up to the claim without context isn't super useful, and unfortunately I rarely think we have the context needed to make them useful. At least by aligning them with the XR or a composed MR you get a good idea of which piece of the puzzle is failing, specifically.

[^1]: In practice we don't try to model external system schema in our own MR schema, because it's too hard to keep up. i.e. What may be a valid field "downstream" in the cloud provider one day won't be the next. Sure an integer field probably won't become a string upstream, but the max value may change from 10 to 1000. Basically we suffer from the same issue at the MR level as @yhrn points out at the claim level.

**Comment by negz** [comment] 2023-05-25 00:36
Throwing out some other options here. We could:

* Ensure all events pertaining to resources derived from a particular claim are labeled consistently. This would allow you to `kubectl get events -l crossplane.io/claim-name=example` and see all Kubernetes events that pertained to the claim, its XR, and its composed resources in one place.
* Update claim status to distinguish between an XR that is not yet ready and an XR that is known to be in an error state.
* Include a breakdown of composed resource readiness (per the readiness checks configured in the Composition) in XR and claim status. This would at least let you 'skip' the XR as a claim author and go straight to looking at the offending MR if one of N is not ready. This would be leaning into the leakiness a bit, and would often be pretty verbose.

**Comment by yhrn** [comment] 2023-06-21 14:49
@negz @sttts really sorry for not responding earlier - I need to get my GitHub notifications in order.

> Now let me touch on how I see Crossplane's abstractions, and perhaps cloud abstractions in general. The quick version is I don't think developers can ignore how the sausage is made. I think the abstraction should leak.

I agree with this, but I only want to leak from the Cloud Machinery, not the Crossplane Machinery. I think it is relevant for the claim author to understand that their Bucket claim resulted in both an S3 bucket and an IAM policy binding, but I don't think it's useful for them to understand what a managed resource or composite resource is.

> * Ensure all events pertaining to resources derived from a particular claim are labeled consistently. This would allow you to `kubectl get events -l crossplane.io/claim-name=example` and see all Kubernetes events that pertained to the claim, its XR, and its composed resources in one place.
> * Update claim status to distinguish between an XR that is not yet ready and an XR that is known to be in an error state.
> * Include a breakdown of composed resource readiness (per the readiness checks configured in the Composition) in XR and claim status. This would at least let you 'skip' the XR as a claim author and go straight to looking at the offending MR if one of N is not ready. This would be leaning into the leakiness a bit, and would often be pretty verbose.

I would love all of these! Especially the last bullet could give us what we need to show the claim author enough information for them to be able to figure out if they can fix it themselves or need to contact the platform team. It should preferably include the following information: 

* The information that can typically be found in the MR "Synced" condition message, i.e. the information from the cloud provider on why something isn't working.
* The external name - this would allow us to not talk the cloud machinery instead of the Crossplane machinery
* All managed resources are included, i.e. the MRs of nested XRs 

This absolutely won't be perfect, e.g. it might not be easy to determine what claim field (if any) caused a specific external resource problem, but I think it would be good enough. In many cases just seeing the error messages from the cloud provider could put the claim author on the right track and for the other cases it's probably fine to ask the platform team for help.

**Comment by yangyang919** [comment] 2023-08-29 08:53
Our end-user met a same case as @erikgb described. End-user creates a claim, but it's stuck with waiting for a very long time:

`status:
  conditions:
  - lastTransitionTime: "2023-08-29T08:26:59Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2023-08-29T08:26:58Z"
    reason: Composite resource claim is waiting for composite resource to become Ready
    status: "False"
    type: Ready`

End-user has no idea what's going on and where went wrong. Then admin check the XR layer, which find the root cause:

`  conditions:
  - lastTransitionTime: "2023-08-29T08:26:58Z"
    message: 'cannot compose resources: cannot apply composed resource: cannot create
      object: Account.storage.azure.upbound.io "agatkaa" is invalid: [spec.forProvider.tags:
      Invalid value: "string": spec.forProvider.tags in body must be of type object:
      "string", <nil>: Invalid value: "null": some validation rules were not checked
      because the object was invalid; correct the existing errors to complete validation]'
    reason: ReconcileError
    status: "False"
    type: Synced`

**Comment by negz** [comment] 2024-02-27 20:02
/fresh

I could see an argument that this would be fixed (in spirit) by https://github.com/crossplane/crossplane/pull/5426 once implemented.

**Comment by jeanduplessis** [comment] 2024-09-03 11:57
With Crossplane v1.17, the ability to communicate claim status/errors/conditions is now available: https://github.com/crossplane/crossplane/issues/5402 

Since this feature addresses the spirit of this request, I will close this issue. 
If a specific use case is not being accommodated by this capability, I suggest opening a new issue specifically to discuss it.

**Closed by jeanduplessis** 2024-09-03 11:57 UTC
Labels: enhancement, user experience
