### ISSUE TITLE
Crossplane on EKS - growth in audit logging - version 1.14.0

### ISSUE THREAD

**Issue by portswigger-tim** [crossplane/crossplane#5074] opened 2023-11-30 11:53 UTC
### What happened?
Large growth in EKS audit and api logs since upgrading to Crossplane 1.14.0 - maybe a regression to behaviour seen in #3540 

Has anyone noticed anything similar? 

I only noticed when I saw the $5K CloudWatch bill 😬

**Comment by portswigger-tim** [comment] 2023-12-01 09:43
**CloudWatch Logs Insights - version 1.14.0**    
region: eu-west-1    
log-group-names: /aws/eks/bsee-dev/cluster    
start-time: 2023-11-27T10:00:00.000Z    
end-time: 2023-11-27T11:00:00.000Z    
query-string:
  ```
  fields @timestamp, @message, @logStream, strlen(@message) as size, concat(verb, ' ', objectRef.apiGroup, '/', objectRef.apiVersion, '/', objectRef.resource) as action
| filter @logStream like 'kube-apiserver-audit'
| filter user.username='system:serviceaccount:crossplane-system:crossplane'
| stats count(*) as count by action
| sort by count desc
  ```
---
| action | count |
| --- | --- |
| update apiextensions.k8s.io/v1/customresourcedefinitions | 899983 |
| get /v1/secrets | 235654 |
| update pkg.crossplane.io/v1/providerrevisions | 78536 |
| patch /v1/secrets | 78533 |
| patch apps/v1/deployments | 39268 |
| patch /v1/serviceaccounts | 39268 |
| patch /v1/services | 39267 |
| get coordination.k8s.io/v1/leases | 2908 |
| update coordination.k8s.io/v1/leases | 1791 |
| get helm.crossplane.io/v1alpha1/releases | 400 |
| patch /v1/events | 292 |
| get kubernetes.crossplane.io/v1alpha1/objects | 212 |
| patch helm.crossplane.io/v1alpha1/releases | 196 |
| patch kubernetes.crossplane.io/v1alpha1/objects | 104 |
| get apps.portswigger.cloud/v1alpha1/bseeinstances | 95 |
| update apps.portswigger.cloud/v1alpha1/bseeinstances | 94 |
| list apps.portswigger.cloud/v1alpha1/bytebininstances | 80 |
| patch apps.portswigger.cloud/v1alpha1/bseeinstances | 48 |
| watch apps.portswigger.cloud/v1alpha1/bseeinstances | 32 |
| watch apps.portswigger.cloud/v1alpha1/licenseonlyinstances | 32 |
| watch apiextensions.k8s.io/v1/customresourcedefinitions | 30 |
| update apps.portswigger.cloud/v1alpha1/licenseonlyinstances | 24 |
| get apps.portswigger.cloud/v1alpha1/licenseonlyinstances | 24 |
| patch pkg.crossplane.io/v1/providerrevisions | 21 |
| update pkg.crossplane.io/v1/providers | 21 |
| watch pkg.crossplane.io/v1/configurations | 18 |
| watch apiextensions.crossplane.io/v1/compositeresourcedefinitions | 18 |
| watch /v1/secrets | 18 |
| watch pkg.crossplane.io/v1beta1/functionrevisions | 18 |
| watch pkg.crossplane.io/v1/configurationrevisions | 18 |
| watch /v1/services | 16 |
| watch apps/v1/deployments | 16 |
| watch pkg.crossplane.io/v1beta1/locks | 16 |
| watch apiextensions.crossplane.io/v1/compositions | 16 |
| watch apiextensions.crossplane.io/v1/compositionrevisions | 16 |
| watch /v1/serviceaccounts | 16 |
| watch pkg.crossplane.io/v1/providerrevisions | 16 |
| watch pkg.crossplane.io/v1beta1/deploymentruntimeconfigs | 16 |
| watch pkg.crossplane.io/v1alpha1/controllerconfigs | 16 |
| create /v1/events | 16 |
| watch pkg.crossplane.io/v1/providers | 14 |
| watch pkg.crossplane.io/v1beta1/functions | 14 |
| patch apps.portswigger.cloud/v1alpha1/licenseonlyinstances | 12 |
| update apiextensions.crossplane.io/v1/compositeresourcedefinitions | 8 |
| create helm.crossplane.io/v1alpha1/releases | 4 |
| create kubernetes.crossplane.io/v1alpha1/objects | 2 |
| create /v1/secrets | 1 |
---

**Comment by portswigger-tim** [comment] 2023-12-01 09:44
**CloudWatch Logs Insights - version 1.13.2**    
region: eu-west-1    
log-group-names: /aws/eks/bsee-dev/cluster    
start-time: 2023-10-27T09:00:00.000Z    
end-time: 2023-10-27T10:00:00.000Z    
query-string:
  ```
  fields @timestamp, @message, @logStream, strlen(@message) as size, concat(verb, ' ', objectRef.apiGroup, '/', objectRef.apiVersion, '/', objectRef.resource) as action
| filter @logStream like 'kube-apiserver-audit'
| filter user.username='system:serviceaccount:crossplane-system:crossplane'
| stats count(*) as count by action
| sort by count desc
  ```
---
| action | count |
| --- | --- |
| get helm.crossplane.io/v1alpha1/releases | 7976 |
| update apiextensions.k8s.io/v1/customresourcedefinitions | 7964 |
| get kubernetes.crossplane.io/v1alpha1/objects | 4820 |
| patch helm.crossplane.io/v1alpha1/releases | 3988 |
| get coordination.k8s.io/v1/leases | 2903 |
| patch kubernetes.crossplane.io/v1alpha1/objects | 2410 |
| update coordination.k8s.io/v1/leases | 1788 |
| get apps.portswigger.cloud/v1alpha1/bseeinstances | 1578 |
| update apps.portswigger.cloud/v1alpha1/bseeinstances | 1578 |
| get apps.portswigger.cloud/v1alpha1/licenseonlyinstances | 1546 |
| update apps.portswigger.cloud/v1alpha1/licenseonlyinstances | 1546 |
| patch apps.portswigger.cloud/v1alpha1/bseeinstances | 789 |
| patch apps.portswigger.cloud/v1alpha1/licenseonlyinstances | 773 |
| update pkg.crossplane.io/v1/providerrevisions | 708 |
| patch /v1/events | 583 |
| patch /v1/serviceaccounts | 248 |
| patch apps/v1/deployments | 248 |
| patch /v1/services | 248 |
| patch pkg.crossplane.io/v1/providerrevisions | 216 |
| update pkg.crossplane.io/v1/providers | 216 |
| get apps.portswigger.cloud/v1alpha1/bytebininstances | 118 |
| update apps.portswigger.cloud/v1alpha1/bytebininstances | 118 |
| delete /v1/services | 106 |
| delete /v1/serviceaccounts | 106 |
| delete apps/v1/deployments | 106 |
| update apiextensions.crossplane.io/v1/compositeresourcedefinitions | 72 |
| patch apps.portswigger.cloud/v1alpha1/bytebininstances | 59 |
| watch pkg.crossplane.io/v1/configurationrevisions | 16 |
| watch apps.portswigger.cloud/v1alpha1/bytebininstances | 16 |
| watch apiextensions.crossplane.io/v1/compositionrevisions | 16 |
| watch apps.portswigger.cloud/v1alpha1/bseeinstances | 16 |
| watch apiextensions.k8s.io/v1/customresourcedefinitions | 16 |
| watch pkg.crossplane.io/v1/configurations | 16 |
| watch apps/v1/deployments | 16 |
| watch apps.portswigger.cloud/v1alpha1/licenseonlyinstances | 16 |
| watch pkg.crossplane.io/v1beta1/locks | 16 |
| watch pkg.crossplane.io/v1alpha1/controllerconfigs | 16 |
| watch apiextensions.crossplane.io/v1/compositions | 14 |
| watch /v1/secrets | 14 |
| watch pkg.crossplane.io/v1/providerrevisions | 14 |
| watch /v1/services | 14 |
| watch /v1/serviceaccounts | 14 |
| watch apiextensions.crossplane.io/v1/compositeresourcedefinitions | 14 |
| watch pkg.crossplane.io/v1/providers | 12 |
| create /v1/events | 4 |
---

**Comment by portswigger-tim** [comment] 2023-12-01 10:28
logs from one of the audit log streams for the same period related to "crossplane update". It seems to be continuously updating CRDs 🤔 - there is only one providerrevision for each provider. 

[log-events-viewer-result.csv](https://github.com/crossplane/crossplane/files/13524349/log-events-viewer-result.csv)

**Comment by phisco** [comment] 2023-12-12 11:55
@portswigger-tim did you manage to understand what happened? 🤔

**Comment by portswigger-tim** [comment] 2023-12-13 13:46
@phisco - Yeh, fixed it.

**Comment by portswigger-tim** [comment] 2023-12-13 13:47
@phisco - That was a StackOverflow joke - I turned off EKS Audit logs until I have time (and energy) to investigate further.

**Comment by jbw976** [comment] 2023-12-13 17:54
Thanks for the update @portswigger-tim, and the humor as well - reminds me a bit of https://xkcd.com/979/ 😂 

We'll keep this issue open because @phisco and I are still concerned about this behavior and hope to find time to investigate further soon. Thanks again for reporting this and glad you've got a bandaid for now at least 🤕

**Comment by mzingarelli** [comment] 2024-02-06 14:19
We are facing the same issue after upgrading to 1.14. Running a single provider revision of provider-family-aws, provider-kms-aws, provider-iam-aws and provider-s3-aws.

Company policy forces us to enable the Audit log.
A possible solution is to create a AWS lambda for log filtering, a subscription and another filtered log group.
Unfortunately EKS doesn't have the audit policy CRD enabled else it could be filtered like [this](https://kubernetes.io/docs/tasks/debug/debug-cluster/audit/)

Using the same Logs Insights query as @phisco over 12h:

[logs-insights-results.csv](https://github.com/crossplane/crossplane/files/14181384/logs-insights-results.csv)

**Comment by dom38** [comment] 2024-02-08 17:33
We've unfortunately been bitten by this as well, our logs generated went up by about 15 times and we didn't catch for 3 weeks. Need to keep the audit logs on unfortunately.

I've set the following in the helm chart values:

```
args:
        - --max-reconcile-rate=1
```
Now our generated logs are only 2 times the size, unfortunately 1 is the lowest it goes but the default was 10.

**Comment by turkenh** [comment] 2024-02-09 09:38
Could there be any other controller/webhook interacting with the CRDs that Crossplane is managing, e.g. something trying to add some common annotations/labels? Also Crossplane debug logs would be helpful indeed.

---

Trying to reproduce this. With the expectation to see CRDs being updated (e.g. their resource versions changing), I've installed Crossplane v1.14.5 and a bunch of providers. Once all are ready, I did run a `kubectl get crds -w` and trying to see some updates but seeing no changes even I restart Crossplane (hence the package manager). When I checked the source code, I am noticing that we're making a [client.Update call](https://github.com/crossplane/crossplane/blob/9db12b7646f1b4ec951571016f119ca76ed8d1be/internal/controller/pkg/revision/establisher.go#L465) but apparently it is not making any change on the CRD. 

So far, we have been thinking we could make an Update call and let the Kube APIServer decide whether a change is required on the resource or not (a very [recent discussion](https://github.com/crossplane/crossplane/pull/5313#discussion_r1477753592) //cc @negz @phisco), but looks like this would cause audit logs since we would need to make the call to API server anyways even though it is a no-op.

This doesn't answer why we started seeing it after v1.14 though, which needs further investigation. However, with the default poll interval of [1mins ](https://github.com/crossplane/crossplane/blob/9a2971f629e70e913bc76d2faf5bbecdbecdb2e3/cmd/crossplane/core/core.go#L101) and the existing implementation, what is happening feels expected to me indeed.

**Comment by turkenh** [comment] 2024-03-15 06:43
We've identified the root cause of the other similar issue and could be the same here: https://github.com/crossplane/crossplane/issues/5458#issuecomment-1999033251

Basically, could you confirm whether you're using a shared service account between multiple providers and configure it with a `ControllerConfig` ?

**Comment by dom38** [comment] 2024-04-10 12:32
I'm testing this today in AWS, will report back after I get some meaningful info

**Comment by dom38** [comment] 2024-04-10 13:14
All right, looking good.

In one environment I reverted my change above where the reconcile rate was reduced from 10 to 1, the changed the deploymentRuntimeConfigs we were deploying to use a service account made alongside to this:

```
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: {{ .Values.providers.kubernetes.controllerConfigName }}
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          serviceAccountName: provider-kubernetes
          containers: []
```
The provider-kubernetes ServiceAccount has the role bindings to make kubernetes objects. We have another deploymentRuntimeConfig for the AWS access which I changed in a similar fashion, making a ServiceAccount with my role annotation.

Using the following log insights query:

```
fields @timestamp, @message, @logStream, strlen(@message) as size, concat(verb, ' ', objectRef.apiGroup, '/', objectRef.apiVersion, '/', objectRef.resource) as action
| filter @logStream like 'kube-apiserver-audit'
| filter user.username='system:serviceaccount:crossplane-system:crossplane'
| filter action='update apiextensions.k8s.io/v1/customresourcedefinitions'
| stats count(*) as count by action
| sort by count desc
```
Below is the number of logs pre-change (Reconcile rate = 1):
![Screenshot_20240410_134901](https://github.com/crossplane/crossplane/assets/19528009/12ec354a-30d0-41e1-bef2-106889c7a5f7)

Below is the number of logs post-change (Reconcile rate = 10):

![Screenshot_20240410_134952](https://github.com/crossplane/crossplane/assets/19528009/64f40db8-1fa2-4112-bf95-494b33806c9b)

Total number of logs dropped from 30k at reconcile-rate=1, to 10k at reconcile-rate=10. With the same reconcile rate I think it was 300k per hour, so nice drop there.

Two issues that I have, both documentation-based:

1. Following the docs to set up the deploymentRuntimeConfigs you will blow your log budget on EKS, and in my case not know about it til end of the month. I'm sure this behaviour isn't desired but a quick fix could be to highlight this in the docs?
2. The spec for the deploymentRuntimeConfigs, I couldn't find a nice page for it and was just looking through the CRD to figure out where the values I needed to put on there. This is probably a skill issue.

**Comment by jeanduplessis** [comment] 2024-04-12 12:20
@dom38 Would you mind raising those two issues on the docs repo at https://github.com/crossplane/docs ? I agree they are worth addressing.

I'll close this issue for now.

**Closed by jeanduplessis** 2024-04-12 12:20 UTC
Labels: bug

**Comment by jbw976** [comment] 2024-04-12 12:35
> The spec for the deploymentRuntimeConfigs, I couldn't find a nice page for it

@dom38 does this link help you with the API docs for `DeploymentRuntimeConfig`? I really like the experience that @plumbis has built there to explore all the Crossplane types/fields:
https://docs.crossplane.io/v1.15/api/#DeploymentRuntimeConfig-spec

> Total number of logs dropped from 30k at reconcile-rate=1, to 10k at reconcile-rate=10. With the same reconcile rate I think it was 300k per hour, so nice drop there.

It sounds like you're seeing a 30x improvement (300k --> 10k) in logs after making the change described in https://github.com/crossplane/crossplane/issues/5458#issuecomment-1999033251, so thanks for sharing your numbers on that!
