### ISSUE TITLE
Reduce the wait time for composition readiness

### ISSUE THREAD

**Issue by vinsguru** [crossplane/crossplane#2555] opened 2021-09-05 20:59 UTC
First of all, thanks to **_crossplane_** team for creating this awesome project & their contribution.

I have been playing with crossplane for the past few days. Overall, I love it. 

I do see some kind of weird behavior in my composition. If we could improve this, it would be great. I create a simple **composition** over aws bucket. It works just great. But it takes `~30seconds` to become ready whereas the underlying resource is already ready within few seconds.

Check the attached screenshot:

![image](https://user-images.githubusercontent.com/6864530/132141118-1168ad43-1ba9-4a71-aa39-2fb85c08ad78.png)

**_bucket_** is crossplane resource. **_s3bucket_** is my composition. The bucket is ready in 5 seconds. but s3bucket is not ready for 30 seconds. (I am not creating any other resource as part of composition).
This is the base in composition.

```
  resources:
  - name: bucket
    base:
      apiVersion: s3.aws.crossplane.io/v1beta1
      kind: Bucket
      spec:
        forProvider:
          acl: private
          locationConstraint: us-east-1
          paymentConfiguration:
            payer: BucketOwner
```

**Comment by negz** [comment] 2021-09-10 03:01
Thanks for raising this @vinsguru! I completely agree that this should happen faster. The issue is that we currently have a fixed 30 second polling interval when we're waiting for something to happen. We have https://github.com/crossplane/crossplane/issues/2157 to track using a faster polling interval (with exponential backoff). Since solving that issue will solve this one, I'm going to close this as a duplicate.

**Closed by negz** 2021-09-10 03:01 UTC
Labels: enhancement
